### ISSUE TITLE
Significant CPU consumption when a channel is open

### ISSUE THREAD

**Issue by tollfree** [overtake/TelegramSwift#1014]
HI folks,
Here is some app behavior I noticed in few months:
Activity Monitor shows 15-20% of CPU load when the app is open, and focus is on any **channel**.
This CPU consumption persists all the time the app is open and newer falls as lower as15%, even the app is in the background, or the app window is closed by Cmd+W.
After switching to another kind of content, a chat or a bot, CPU load quickly falls to <1%.

Checked on two separate Macs.

Reinstall, switch from MAS version to the website downloaded, completely wipe and install in a new account didn't resolve the problem.
The app eats ~10% of energy permanently even it's just first time launched, with no accounts logged in.
And   #829 issue is in place, too.

It forced me to temporarily (I hope) switch to TD version, this app has no such problems.

Version: 10.0.4
Mac M1, macOS: 13.5.2

**Comment by VadimMuhtarov** [comment]
Same problem. 
10.0.5.250883 AppStore, Sonoma, Air M2

**Comment by dimaleks** [comment]
Same here. For me though _some_ channels don't increase the CPU load, but most still do.
10.0.5.250883 App Store, Mac OS 13.4.1 (22F770820d), MacBook Air M2, 16 GB
