### ISSUE TITLE
Sticker selecting view needs to update its background color whem theme changed

### ISSUE THREAD

**Issue by GRiMe2D** [overtake/TelegramSwift#104]
## How to reproduce
1. Open telegram
2. Change theme to other one (for example to Dark)
3. Try to send a sticker

_Restarting telegram applies proper background color_

<img width="489" alt="screen shot 2018-02-07 at 6 43 59 pm" src="https://user-images.githubusercontent.com/6705445/35925566-1a05802e-0c37-11e8-8b2e-8b8a785ec2a7.png">

**Comment by zweeltow** [comment]
Fixed.
