### ISSUE TITLE
Версия 10.4 Не работает под 10.13.6 (17G14042)

### ISSUE THREAD

**Issue by MaximvsStorm** [overtake/TelegramSwift#1052]
Версия 10.4 Не работает вообще под 10.13.6 (17G14042)

**Comment by overtake** [comment]
Нужно вручную скачать с сайта macOS.telegram.org

**Comment by MaximvsStorm** [comment]
Именно эта версия и не работает. Мне похер, но сам факт! Проблема у вас, а не у меня.

**Comment by overtake** [comment]
https://t.me/macos_stable_updates_files/236

Установите этот файл

**Comment by MaximvsStorm** [comment]
Спасибо. Заработало. Тему можно закрыть.
