### ISSUE TITLE
Option to disable calling for desktop

### ISSUE THREAD

**Issue by SAGV** [overtake/TelegramSwift#106]
It is issue similar to:
https://www.reddit.com/r/Telegram/comments/7efccw/how_do_i_disable_incoming_calls_popping_up_in_the/
https://github.com/telegramdesktop/tdesktop/issues/4002

So when someone calls me on Telegram, I'd prefer to receive call notifications only on my phone. Not on my mac. But there is currently no way to disable a loud sound and a big "You are called" popup on the mac without quitting the app itself.

Preferably, I'd want to completely disable any calling functionality on the mac app and only keep it on the phone.

**Comment by dadee** [comment]
absolutely neccessary option

**Comment by ketanmehta** [comment]
Much needed functionality.

**Comment by maxfarseer** [comment]
Agree here, +1

**Comment by MrPrep** [comment]
Please, why is this not a feature already after 3 years from the reddit post?
Or at least make "Desktop notifications" and "Play sounds" options also work for calls, why do they only apply to chats in the first place?

**Comment by yangm97** [comment]
The most annoying thing is calls completely ignore the "do not disturb" macOS setting. 

Got fed up of this issue and disabled telegram calls altogether.

**Comment by 3pns** [comment]
Telegram is supposed to be all about privacy. Yet it does not have basic features to prevent others to invade our privacy.
This should be a top priority feature

**Comment by rdednl** [comment]
Not only telegram overriding the DND macOS setting, but also, if you mute a contact chat, this contact can still call you and invade your screen completely.

**Comment by voiceoverblogs** [comment]
hey guys, check this link which explains that there are 2 official apps from Telegram for iOS, its part of Telegram FAQ's

"https://telegram.org/faq#q-why-do-you-have-two-apps-in-the-mac-app-store"

thy this second app for Mac "https://desktop.telegram.org"

, this installs a lighter version of Telegram and this works fantastic...no desktop pop ups for incoming calls, the calls just ring on your iPhone.....worked well for me !


> Not only telegram overriding the DND macOS setting, but also, if you mute a contact chat, this contact can still call you and invade your screen completely.



> Telegram is supposed to be all about privacy. Yet it does not have basic features to prevent others to invade our privacy.
> This should be a top priority feature



> It is issue similar to: https://www.reddit.com/r/Telegram/comments/7efccw/how_do_i_disable_incoming_calls_popping_up_in_the/ [telegramdesktop/tdesktop#4002](https://github.com/telegramdesktop/tdesktop/issues/4002)
> 
> So when someone calls me on Telegram, I'd prefer to receive call notifications only on my phone. Not on my mac. But there is currently no way to disable a loud sound and a big "You are called" popup on the mac without quitting the app itself.
> 
> Preferably, I'd want to completely disable any calling functionality on the mac app and only keep it on the phone.

**Comment by spss20** [comment]
wtf, Why there is no feature to diable calls in telegram osx app even after the issue was reported 3 years back , that a huge time.

**Comment by vitalii427** [comment]
+1

**Comment by ashiqkareem** [comment]
cmon guys its been so long i have to use the telegram lite application for this simple feature...

**Comment by hiivan** [comment]
it's going to be 2023 in a few days and still no update..

**Comment by dmserebr** [comment]
Please add this!! This is really annoying.
I love the native macOS client but I suffer from hearing ringtones on the laptop every time. And there is no workaround.

**Comment by twopac** [comment]
5 years since this issue was opened. A lot of people suffering every day from this problem. Please fix it

**Comment by overtake** [comment]
you can disable incoming calls Settings->Active Session-> Click on your current session or check desired.

**Comment by murtajata** [comment]
@overtake thank you so much!!

**Comment by overtake** [comment]
i will add this toggles to notifications settings too. maybe it might help.

**Comment by dmser1** [comment]
@overtake I tried this option now and the behavior is weird. I go to Active Sessions, open current session (which is a MacOS session) and see 2 toggles, for "New Secret Chats" and "Incoming Calls". They are both on by default.

If I turn off only the incoming calls and close popup, and then open it again, I see that both toggles are on (i.e., "New Secret Chats" and "Incoming Calls"), so I cannot disable incoming calls.
If I turn off only the secret chats and close popup, and then open it again, I see that both toggles are off.
This happens for other sessions as well (not only the current one).

It looks like the "incoming calls" toggle does not work or does show the status of the "new secret chats" toggle for some reason.

I found this on MacOS 13.0.1 (Apple Silicon), client version is 9.4.1.243742 Stable

**Comment by overtake** [comment]
> @overtake I tried this option now and the behavior is weird. I go to Active Sessions, open current session (which is a MacOS session) and see 2 toggles, for "New Secret Chats" and "Incoming Calls". They are both on by default.
> 
> If I turn off only the incoming calls and close popup, and then open it again, I see that both toggles are on (i.e., "New Secret Chats" and "Incoming Calls"), so I cannot disable incoming calls. If I turn off only the secret chats and close popup, and then open it again, I see that both toggles are off. This happens for other sessions as well (not only the current one).
> 
> It looks like the "incoming calls" toggle does not work or does show the status of the "new secret chats" toggle for some reason.
> 
> I found this on MacOS 13.0.1 (Apple Silicon), client version is 9.4.1.243742 Stable

I fixed it. should be ok in 9.4.2 and also you find those settings in notifications and sounds
