### ISSUE TITLE
[Bug] Video-stickers are not playing

### ISSUE THREAD

**Issue by mihail-jdanov** [overtake/TelegramSwift#1063]
Video-stickers are displayed as static pictures.
Sticker pack example: https://t.me/addstickers/AlexVideoMemes

Version: 10.6.258482 Stable

**Comment by overtake** [comment]
what is your device?

пт, 19 янв. 2024 г. в 17:04, Mikhail Zhdanov ***@***.***>:

**Comment by mihail-jdanov** [comment]
MacBook Pro 15 2015 and iMac M1.
Today I updated to the latest version (10.6.258516 Stable) and stickers playing normally on it.
