### ISSUE TITLE
Did the TelegramSwift project stop being open source?

### ISSUE THREAD

**Issue by xiky** [overtake/TelegramSwift#1075]
My Telegram has updated a few times, but the code in the project is still two months old.

**Comment by AprilNEA** [comment]
In conjunction with #1060, I have concerns about the security of TelegramSwift.

**Comment by alex-kinokon** [comment]
I don’t think it was to begin with. You couldn’t even build it.

**Comment by overtake** [comment]
i pushed the latest source code.  you can check it
