### ISSUE TITLE
Apply to add multiple accounts

### ISSUE THREAD

**Issue by oky2abbas** [overtake/TelegramSwift#109]
Hello . Please add the ability to add multiple accounts to this version of the Mac Telegram.
Multi-platform desktop telegram has a problem with using too much CPU and I do not like to use it.

Please add the requested functionality. Thanks.

**Comment by gamato** [comment]
Hi, indeed! This is very important feature. Android app has it too already, macOS desktop app should not be left behind. Many thanks!

**Comment by dfmabbas** [comment]
+1

**Comment by dfmabbas** [comment]
+1

**Comment by overtake** [comment]
implemented for 5.0
