### ISSUE TITLE
Automatic Media Download

### ISSUE THREAD

**Issue by functtor** [overtake/TelegramSwift#11]
It'd be great to have the option to enable/disable automatic media download for images/gifs/videos/voices.

**Comment by seriiix** [comment]
Still waiting for this feature

**Comment by itsN0ll** [comment]
i'm waiting for this to ... 🙄

**Comment by sawrubh** [comment]
@overtake is this feature implementation blocked by something else?

**Comment by overtake** [comment]
added to beta. wait for stable release

**Comment by sawrubh** [comment]
Is there an option to enable the beta channel updates on the stable release (like for example there is an option inside WhatsApp Desktop client)? How can one can go and test out the beta version?
