### ISSUE TITLE
Videos can be saved in channel posts protected mode

### ISSUE THREAD

**Issue by akbarali1** [overtake/TelegramSwift#1129]
I have uploaded videos on my channel and disabled the download of those videos. But it can be saved to a folder on the Download page

https://github.com/overtake/TelegramSwift/assets/39323182/752b9934-aa24-4a3d-9d3e-4b6b29f374e9

**Comment by zweeltow** [comment]
It was sent as a file, not just a photo/video. So it's not a bug.
