### ISSUE TITLE
[Feature] Ability to respond to join requests as admin

### ISSUE THREAD

**Issue by SuibianP** [overtake/TelegramSwift#1138]
Telegram has the feature of [join requests](https://core.telegram.org/api/invites#join-requests), which allows group admins to have an approval process for specified invite links.

The feature currently seems absent in Telegram for macOS, and users awaiting approval are not displayed anywhere for admin action.

**Comment by zweeltow** [comment]
Group/Channel Info > Edit > Join Requests
