### ISSUE TITLE
[BUG] Force replacing my text to emoji

### ISSUE THREAD

**Issue by Verdgil** [overtake/TelegramSwift#1141]
When i write some list, for example like this

```
...
7) Some text
8) Some text
9) Some text
...
```

"8)" replace to "😍"

------------------------------------

Когда я набираю какой-то список, как например, тот, что выше, "8)" заменяется на "😍"

<img width="1135" alt="изображение" src="https://github.com/overtake/TelegramSwift/assets/3881312/6512f725-207c-4199-ad2d-92f7e581b5cc">
<img width="198" alt="изображение" src="https://github.com/overtake/TelegramSwift/assets/3881312/13732b17-6d2e-4444-b18f-c0fb65f61c4b">

Settings/Настройки:
<img width="626" alt="изображение" src="https://github.com/overtake/TelegramSwift/assets/3881312/dd0e40dd-517c-4e55-987d-eb15b2c29b73">

Version: 10.15.2.265540 Stable
OS: macOS 14.1.2 (23B92)

**Comment by jainamoswal** [comment]
This is not a bug but a feature where certain texts replaces with emojis. 

Like:  
- `:)` → 🙂
- `:(` → 😕
- `8)` → 😍


You can turn this setting off. 
Profile > General > Emoji Section > Replace Emoji Automatically. 
![image](https://github.com/overtake/TelegramSwift/assets/76057348/c19579dc-75ae-4195-a479-bff2bf1ce199)

**Comment by Verdgil** [comment]
O, in some version this settings is gone. But right now it returns
