### ISSUE TITLE
Close Button Not Working for Instant View

### ISSUE THREAD

**Issue by antonlukin** [overtake/TelegramSwift#1146]
**Description:**
When opening an article in Instant View within a popup, the window cannot be closed. Clicking the close (X) button instead maximizes the window to full screen.

**Steps to Reproduce:**
Open an article in Instant View in a popup.
Attempt to close the window by clicking the close (X) button.
Expected Behavior:
The popup window should close when the close (X) button is clicked.

**Actual Behavior:**
Clicking the close (X) button maximizes the popup window to full screen instead of closing it.

**Additional Information:**
macOS Sonoma,
Telegram 10.15.2.265540 Stable

https://github.com/user-attachments/assets/598258d4-d7f2-44ab-95f3-0453f344520c

**Comment by kosmgco** [comment]
same issue here

**Comment by kosmgco** [comment]
Fixed in 10.15.4.266656 Stable
