### ISSUE TITLE
View / Enter Full Screen menu is not updated

### ISSUE THREAD

**Issue by slavaGanzin** [overtake/TelegramSwift#1154]
Hello

Minor bug: Telegram displays View / Enter Full Screen in the menu regardless of full screen mode. Teams and a lot of other apps shows View / Exit Full Screen when it is already activated.

Kinda messes up with my automations :)

<img width="414" alt="Screenshot 2024-08-05 at 14 00 18" src="https://github.com/user-attachments/assets/84bfd4ee-a3f1-43d1-9267-0e61bc8b7abb">

version: 10.15.4.266662 AppStore

**Comment by zweeltow** [comment]
![image](https://github.com/user-attachments/assets/f713627e-f537-4abf-8eb4-39868c88bb41)
Works fine for me at Telegram 10.15.4.266662 Stable and macOS 13.6.4, can't reproduce.

**Comment by slavaGanzin** [comment]
interesting
