### ISSUE TITLE
Can't open any link by click

### ISSUE THREAD

**Issue by iegik** [overtake/TelegramSwift#116]
Telegram v3.7.5.115423
Google Chrome v64.0.3282.167
Mac OS 10.13.3
Clicking on link opens new blank browser window.

**Comment by alexfoo** [comment]
Restart chrome.

It happens for when chrome is updated, but not restarted since I reinstalled Chrome via homebrew. Same for all applications opening chrome (slack, discord, spotify, sublime, iterm) eg. not a Telegram issue.

**Comment by iegik** [comment]
Thanks
