### ISSUE TITLE
Two female waving emojis🙋🏻‍♀️🙋🏻‍♀️🙋🏻‍♀️, no male one🙋🏻‍♂️🙋🏻‍♂️🙋🏻‍♂️

### ISSUE THREAD

**Issue by CoolTomatos** [overtake/TelegramSwift#123]
Today I tried to change the skin colour of the male waving emoji from the default one 🙋‍♂️ to a white one  🙋🏻‍♂️.
After I press it, it changed into the female one. 🙋🏻‍♀️
Now I got two female ones, and no male one.
I am using the swift client from the Mac App Store.

**Comment by ntapiam** [comment]
I'm also having the same issue but with the 🤷🏽‍♂️ emoji

**Comment by CoolTomatos** [comment]
@ntapiam seems like nobody is maintaining this repository.

**Comment by yfede** [comment]
Having a very similar issue:

Steps to reproduce:

1. Open the Emoji panel
2. Find the Emoji of the man with the blackboard in the background: 👨‍🏫
3. Press it to display the skin color variations. 

**Minor problem: in the panel, the "man face" emoji 👨 is displayed in all its variations, not the one with the blackboard behind him, as one would have expected**

4. Now, choose one of the variations (I chose the first, pale skin dark hair)
5. After this step, comes the main problem:

**Main problem: several emojis in the panel now are replaced with the "man face", making it impossible to know which was the original emoji in their place** (see attached screenshot)

![screen shot 2018-06-25 at 11 04 40](https://user-images.githubusercontent.com/639411/41841817-89fd9a9e-7869-11e8-89a1-0595a93d6431.png)

**Unfortunately, restarting the application does NOT restore the correct emojis.**

Does anyone know at least a workaround to restore them?

**Comment by CoolTomatos** [comment]
@yfede what I did is simply reinstall it. since all the chat history is in the cloud, you don't lose anything reinstalling it.

**Comment by ntapiam** [comment]
@CoolTomatos I tried to reinstall several times but the problem persists. Did you erase any other files besides the main .app bundle?
I think this repository is actually being mantained.

**Comment by CoolTomatos** [comment]
@ntapiam hmmm, that's weird. it should work after reinstalling.
