### ISSUE TITLE
Problem with accented characters at the end of messages

### ISSUE THREAD

**Issue by ailnlv** [overtake/TelegramSwift#129]
Starting with version 3.8.1.119441 Stable, if the last character of a message is accented (such as áàâñ), the message is sent with that character deleted, and only the accent (or sometimes an apostrophe) is sent.

For example, if I type

    Sí

The message is sent as

    S´

However, if I append any non accented character (or even a space), the message is sent properly. Accented characters which are not at the end of the message aren't a problem.

**Comment by akira02** [comment]
Maybe there's a similar issue on traditional chinese
![3 -16-2018 21-50-47](https://user-images.githubusercontent.com/4176802/37528576-f3340fe6-296f-11e8-9ee5-cfd0d28bf0d1.gif)

**Comment by overtake** [comment]
sorry for this guys. i fixed it in beta. and will release on next week stable version
