### ISSUE TITLE
Emojis are partially replaced when hitting enter

### ISSUE THREAD

**Issue by domomg** [overtake/TelegramSwift#131]
Kinda similar to:

#50 

The issue happens with version 3.8.1 from the Mac App Store, but this time:

1) if I write a single text emoji, it replaces it in the message preview, but will send it as text.
2) if I write a couple of emojis, it replaces all of them but the last one will be sent as text no matter what.

I went back to version 3.8  (got the non-Store dmg from telegram.org), and everything works as expected, so I guess it's a 3.8.1 regression or something.

See screenshot for reference.

![screen shot 2018-03-17 at 16 51 33](https://user-images.githubusercontent.com/9155311/37557368-bb124102-2a03-11e8-9d3d-b742aa7512d6.png)

**Comment by domomg** [comment]
issue still unfixed on 3.8.2

**Comment by overtake** [comment]
fixed thanks.

**Comment by domomg** [comment]
Hi, thank you, I would like to add that it's still partially broken on the latest update I got today from the Mac App Store (3.8.2):
As of version 3.8.2, if I write an ascii emoji and press enter, it will send it as text (and you barely see it replaced for a split second), I've to press space once to get the proper behaviour.

this is what happens on 3.8.2:

![mar-21-2018 12-28-45](https://user-images.githubusercontent.com/9155311/37707563-d150bcde-2d03-11e8-981f-6d52e0ceff4b.gif)


this is how it is supposed to work, on 3.8.0:

![mar-21-2018 12-30-18](https://user-images.githubusercontent.com/9155311/37707572-d95e6dcc-2d03-11e8-953d-5494c12b0a7c.gif)

**Comment by yochem** [comment]
Same problem here...
the problems seems to be an emoji at the end of a message. When you press space after the emoji it works just fine. 

v3.8.1.119441 stable

**Comment by yochem** [comment]
?

**Comment by yochem** [comment]
thanks.

**Comment by domomg** [comment]
As of version 4.0, the issue seems resolved with the correct old behaviour.

Many thanks!
