### ISSUE TITLE
Problems with enabling proxy settings through link button

### ISSUE THREAD

**Issue by sorrowloki** [overtake/TelegramSwift#138]
Hello, 

On MacOS I discovered strange problem with enabling proxy through link button in bot. 

I do this with https://t.me/socks?server=[server]&port=[port]&user=[usr]&pass=[pwd]

When I click it as usual link, then i can enable proxy setting. Otherwise when i click it through link button, client try to resolve it as telegram channel. 

Please, fix.

**Comment by AlekSi** [comment]
I think that one was fixed.
