### ISSUE TITLE
t.me/socks format

### ISSUE THREAD

**Issue by AlekSi** [overtake/TelegramSwift#145]
https://github.com/overtake/TelegramSwift/blob/e04d88acdbc827827da0c06ccde3cee2dcff2743/Telegram-Mac/ProxySettingsViewController.swift#L389-L399

It seems it should be `user` and `pass` instead of `username` and `password`. At least, that's what [Telegram Desktop uses](https://github.com/telegramdesktop/tdesktop/blob/e0f20e9f82784857780a763b11e0183b797c110a/Telegram/SourceFiles/boxes/connection_box.cpp#L25-L48), and what works in the iOS app in practice.

**Comment by sorrowloki** [comment]
#138 
Dublicate 

Developers, please, fix!

**Comment by AlekSi** [comment]
Duplicate indeed.

**Comment by overtake** [comment]
fixed.
