### ISSUE TITLE
Request: allow for accent color customization on the Dark theme

### ISSUE THREAD

**Issue by pgsill** [overtake/TelegramSwift#172]
With the Day theme, you can choose an accent color:

![hi](https://i.imgur.com/KNEcX1j.png)

But you can't do the same with the Dark theme:

![hi](https://i.imgur.com/g1YmUSh.png)

I love using orange accents wherever I can, but because I love my retinas, I also use dark themes whenever possible.

Check out what happens when you mix the comfortable warmth of orange accents and the cool, eye-pleasing darkness of a dark blue theme on Twitter:

![hi](https://i.imgur.com/52UXvoV.png)
![hi](https://i.imgur.com/UkCc5OS.png)

Pure bliss.

Please add support for accents on the Dark theme.

Thanks!

**Comment by dancojocaru2000** [comment]
Any updates on this?
