### ISSUE TITLE
Search for chats + contacts broken

### ISSUE THREAD

**Issue by themightyoarfish** [overtake/TelegramSwift#176]
Since a few updates ago (I am on 4.1.131203 stable), typing anything in the search bar in the contacts or chats tab results in an empty list.

OSX 10.12.6

**Comment by themightyoarfish** [comment]
The bug does not appear in 3.9.2.125989 Stable

**Comment by overtake** [comment]
Hi. can you contact me with telegram for details? t.me/vihor
