### ISSUE TITLE
Passcode message leak

### ISSUE THREAD

**Issue by mikekosulin** [overtake/TelegramSwift#18]
1. Turn on passcode.
2. Open any chat.
3. Send any photo.
4. Start typing caption for photo.
5. Lock laptop.
6. Unlock laptop.
7. Type your telegram passcode and submit.
8. Congrats, you've just compromised your passcode!
9. Type passcode again and submit for unlock telegram.

Telegram 3.5.107595 Stable
OS X 10.12.6 (16G29)

**Comment by overtake** [comment]
fixed. thanks
