### ISSUE TITLE
Subtle mistake in Main menu application item

### ISSUE THREAD

**Issue by ePirat** [overtake/TelegramSwift#183]
The main menu of the application is incorrect, unlike with all other apps, the name of the app is not bold like it should be:

<img width="312" alt="telegrammenu" src="https://user-images.githubusercontent.com/323210/42653958-4b8b62e4-8617-11e8-9b84-fe62d44ebfda.png">

For comparison, this is what it should look like:

<img width="168" alt="findermenu" src="https://user-images.githubusercontent.com/323210/42653971-5a39e3c4-8617-11e8-935d-33ed19005bba.png">

Tested with 3.9.2.126641 Beta

**Comment by Mnkai** [comment]
Also have this behaviour in 4.7.1.147620 AppStore.

While it's not important, I believe it can be fixed quite easily.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/10909652/49793846-745e3000-fd79-11e8-9b62-12bf997a63ed.png">

<img width="254" alt="image" src="https://user-images.githubusercontent.com/10909652/49793925-a53e6500-fd79-11e8-8e78-c15e0c70d715.png">

**Comment by zweeltow** [comment]
On **6.1.4 (201252) Beta** all right.
