### ISSUE TITLE
Feature request: Show icon with notification count in menubar.

### ISSUE THREAD

**Issue by udenfox** [overtake/TelegramSwift#192]
Native macOS app is really great and optimized, but there is one option that makes in less convenient in use - there is no option to show icon with notification count in menu bar, like it works in Telegram Desktop client.

It's really cool feature for those who use macOS with auto-hide dock, like me. Without that icon it's really easy to miss some notification.

Thanks for good app, btw.

**Comment by Alinaki** [comment]
Landed in latest beta after my moaning in Twitter! :)

**Comment by d3sh** [comment]
Telegram icon is not visible until you click on it (its there, just not visible). I did these adjustments to Mojave Dark theme, may be this causes this effect. Please fix it

https://www.tekrevue.com/tip/only-dark-menu-bar-dock-mojave/
