### ISSUE TITLE
tg://resolve/?domain=telegrampassport posted in chat crashes app

### ISSUE THREAD

**Issue by komachi** [overtake/TelegramSwift#193]
Working on Telegram for macOS 4.2.1 (latest stable).

Opening chat where someone posted `tg://resolve/?domain=telegrampassport` crashes app.

Found it when testing bug discovered by @MihaZupan telegramdesktop/tdesktop#5021 This is worse because you don't even need to click on link.

**Comment by kervmike** [comment]
Good to hear

**Comment by redditblog** [comment]
> Working on Telegram for macOS 4.2.1 (latest stable).
> 
> Opening chat where someone posted `tg://resolve/?domain=telegrampassport` crashes app.
> 
> Found it when testing bug discovered by @MihaZupan [telegramdesktop/tdesktop#5021](https://github.com/telegramdesktop/tdesktop/issues/5021) This is worse because you don't even need to click on link.

**Comment by redditblog** [comment]
> Working on Telegram for macOS 4.2.1 (latest stable).
> 
> Opening chat where someone posted `tg://resolve/?domain=telegrampassport` crashes app.
> 
> Found it when testing bug discovered by @MihaZupan [telegramdesktop/tdesktop#5021](https://github.com/telegramdesktop/tdesktop/issues/5021) This is worse because you don't even need to click on link.

**Comment by Jacqueline131419** [comment]
0x3BAA55619f6F3D3b736FB6d825F7cF5bF31eab86

**Comment by inshum** [comment]
Good pro

**Comment by Pooya22** [comment]
Good project

**Comment by OrigamiBrain** [comment]
open it please
