### ISSUE TITLE
Feature request: Add Telegram to macOS share menu

### ISSUE THREAD

**Issue by dominikue** [overtake/TelegramSwift#196]
Please add telegram to the macOS share menu to easily sharing photos and content in the MacOS System. I think this would be a nice integration for a messenger.

**Comment by overtake** [comment]
working on AppStore version.

**Comment by woj-tek** [comment]
Is this feature AppStore version exclusive? Are there any reasons it's not in regular version?

**Comment by hutattedonmyarm** [comment]
I have the app and telegram is not in the list
<img width="780" alt="screen shot 2018-12-24 at 17 31 50" src="https://user-images.githubusercontent.com/664905/50403768-cd7a8a80-07a1-11e9-8be3-55e347dfbb76.png">

**Comment by Drjacky** [comment]
Same problem here.

**Comment by larssb** [comment]
Guys, ensure that you are actually using `Telegram for MacOS` and not `Telegram Desktop`, they are both available from the AppStore. However, only `Telegram for MacOS` gives us the `Share Menu` option....

@Drjacky @hutattedonmyarm @dominikue

**Comment by woj-tek** [comment]
I asked before:
> Is this feature AppStore version exclusive? Are there any reasons it's not in regular version?

Never got an answer...

**Comment by mnik01** [comment]
facing issue
