### ISSUE TITLE
Support for custom themes

### ISSUE THREAD

**Issue by Canorus** [overtake/TelegramSwift#199]
I was looking for the way to apply custom themes uploaded on group chat, and it turns out, those themes are for Telegram Desktop only, can't apply to TelegramSwift. So I thought it would be great if TelegramSwift can also take those custom themes.

**Comment by zweeltow** [comment]
https://telegram.org/blog/scheduled-reminders-themes#custom-cloud-themes

e.g. https://t.me/addtheme/DraculaMint
