### ISSUE TITLE
[Bug] Stuck on Installing Update

### ISSUE THREAD

**Issue by anton-arsentyev** [overtake/TelegramSwift#20]
Trying to Update my Telegram: 

1. Click Install

![screen shot 2017-10-19 at 14 33 47](https://user-images.githubusercontent.com/22887126/31771016-bbb9a58a-b4da-11e7-9ce5-846172b19e49.png)

2.  Endless waiting...

![screen shot 2017-10-19 at 14 33 52](https://user-images.githubusercontent.com/22887126/31771019-bfb52bd2-b4da-11e7-940e-e0a593f8ddf5.png)

**Comment by overtake** [comment]
version? 3.1?

**Comment by anton-arsentyev** [comment]
@overtake 3.1.1

**Comment by overtake** [comment]
please download update manually telegram.org/dl/macos
