### ISSUE TITLE
Emoji "man shrugging" is not working

### ISSUE THREAD

**Issue by dandaka** [overtake/TelegramSwift#207]
**How**

1. Person on iOS sends "man shrugging" emoji https://emojipedia.org/man-shrugging/
2. Person on Macos see it like this "🤷🏻‍♀️"

**Should be**

Similar display of emojis on both platforms.

**Comment by zweeltow** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/50041341/82830207-c4717980-9ebd-11ea-9ebd-9fafdce68484.png)
