### ISSUE TITLE
No contacts in contacts tab

### ISSUE THREAD

**Issue by chschommer** [overtake/TelegramSwift#208]
Hi,

I switched from "Telegram Desktop" App Store client  to the "Telegram Swift" App Store client.

I can not see any of my contacts in the contacts tab (see image):

<img src="https://user-images.githubusercontent.com/1376630/45836344-e12ed480-bd0c-11e8-8c11-54c8eeb37282.jpeg" width="300">

However, if I start typing in the search bar, my contacts appear (see image): 

<img src="https://user-images.githubusercontent.com/1376630/45836374-f572d180-bd0c-11e8-81c8-4c6ea9e84d12.jpeg" width="300">

I am on a MacBook Pro 15 from 2017 with MacOS 10.12.6 Sierra, Telegram Swift Client 4.3.4.139633 AppStore.

I am not sure, if I did something wrong or this is a bug.

Thanks in advance.

**Comment by overtake** [comment]
Know. Sorry for that.

**Comment by overtake** [comment]
Fixed in beta and will fix in next release version (next week)
