### ISSUE TITLE
mojave: Follow system dark mode

### ISSUE THREAD

**Issue by sergeysova** [overtake/TelegramSwift#209]
macOS Mojave has a system-wide dark mode. It would be nice to have an option to follow the system theme.

Like in [IINA](https://github.com/lhc70000/iina)

https://github.com/electron/electron/issues/13387
https://github.com/mattermost/desktop/issues/848
https://github.com/telegramdesktop/tdesktop/issues/4918
https://github.com/sindresorhus/caprine/issues/510

**Comment by yochem** [comment]
This! 🙏

**Comment by mihaifpopa** [comment]
This would be great! Please add it! Thanks!

**Comment by gustavoavena** [comment]
This would be great!!

**Comment by yochem** [comment]
Thank you for adding this! But when the function is on, I am only allowed to use the default light theme (_Day Classic_). Is it possible to use the theme _Day_ when in light mode and _Dark Mojave_ when in dark mode?

**Comment by tarungavara** [comment]
Please do this. The current blue night mode stands out from the other apps.

**Comment by fenhl** [comment]
Is there a practical reason to restrict this to Mojave? Dark Mode was introduced in Yosemite.

**Comment by fenhl** [comment]
Looks like I was misinterpreting this, #251 is what I meant.
