### ISSUE TITLE
Application badge always at 1 with unread messages

### ISSUE THREAD

**Issue by StefanoFioravanzo** [overtake/TelegramSwift#226]
The notification badge is always at "1", even if there are no unread messages.
With just one chat with unread messages, the badge shows "2" and so on.
![screenshot 2018-10-26 at 09 44 01](https://user-images.githubusercontent.com/3354305/47551911-b59e9b80-d903-11e8-831a-013a57408c47.png)

**Comment by ddobrev** [comment]
I have the same issue, please fix it. It's been a year and a half.

**Comment by zweeltow** [comment]
![image](https://user-images.githubusercontent.com/50041341/82830008-4614d780-9ebd-11ea-8a75-30fb6cf16868.png)
