### ISSUE TITLE
Display bold text by markdown syntax

### ISSUE THREAD

**Issue by neighborhood999** [overtake/TelegramSwift#23]
I type some text with markdown syntax, for example: `Hello, my name is **neighborhood999**`, but send message can't not correct render to markdown.

<img width="486" alt="2017-10-23 3 35 23" src="https://user-images.githubusercontent.com/10325111/31877114-e35af0a4-b79a-11e7-8444-0150edbab9ef.png">

My Telegram desktop version: **3.5.107695**, download from App Store.

**Comment by longnd** [comment]
- this repo is for Telegram native for Mac (written on Swift), the other version is cross-platform version (qt based)
- you may already know that, on Telegram, text formating works like this:
+ bold: select the text & Ctrl B (or right click -> Transformation -> make Bold)
+ italic: select the text & Ctr I (or right click -> Transformation -> make Italic)

AFAIK, markdown is not supported at the moment but I think the current way is easier for a normal user

**Comment by neighborhood999** [comment]
@longnd Thanks for your reply. I just curious about why in [web.telegram.org](https://web.telegram.org/) and on Windows can render markdown syntax correctly. I understand use `Ctrl + B` and `Ctrl + I` may the easiest for use to format text.
