### ISSUE TITLE
4.6.142825 Stable on MacOS displays notifications if there are unread messages in muted groups and channels

### ISSUE THREAD

**Issue by BurkovBA** [overtake/TelegramSwift#231]
### Steps to reproduce
1. Go to settings, disable all triggers in "Badge counter" section:

![screen shot 2018-11-05 at 14 27 43](https://user-images.githubusercontent.com/7602655/48003669-fc13a780-e106-11e8-96b6-ad62d0831116.png)

2. Wait for a new message in public group or channel. The badge counter will display a number:

![screen shot 2018-11-05 at 14 28 28](https://user-images.githubusercontent.com/7602655/48003701-15b4ef00-e107-11e8-980d-2d63012b06d1.png)

3. Open TelegramSwift client. The badge counter in client window will show new messages. If you don't click on those groups/channels, the badge counter in bottom menu bar would sometimes disappear all by itself, and sometimes show up again. I didn't manage to figure out the logic behind this behaviour, sorry.

![screen shot 2018-11-05 at 14 29 13](https://user-images.githubusercontent.com/7602655/48003805-6593b600-e107-11e8-910a-367428a6e283.png)

### Expected behaviour
Badge counter should not include muted channels/public groups.

### Actual behaviour
For each muted channel with unread messages I see a bubble counter increment on Telegram icon in bottom menu bar.

### Configuration
**Operating system:**
MacOS Sierra 10.12.5

**Version of TelegramSwift:**
4.6.142825 Stable

**Used theme**:
default

**Comment by BurkovBA** [comment]
Hm, looks like I should've restarted the client after step 1 (disabling all the triggers in "Badge counter" section).

**Comment by overtake** [comment]
Yes. Thanks you. Working on this.

**Comment by overtake** [comment]
found and fixed. will update stable version. Thanks for report.

**Comment by BurkovBA** [comment]
Thank you for doing a great job on Telegram, it's wonderful!
