### ISSUE TITLE
Update downloading doesn't work

### ISSUE THREAD

**Issue by Webbrother** [overtake/TelegramSwift#236]
OS: macOS Mojave 10.14.1
Telegram version: 4.6.1.143379 Stable
The issue also was reproducing with older versions of OS and telegram.

Update downloading doesn't work in Russia.
When I push "download and install update" button downloading fail, so update doesn't install.
But it works correct when I use VPN.

I guess the issue is related to Russia government internet censorship. But if telegram works within such conditions I expect that update also should work. But it doesn't.

**Comment by zweeltow** [comment]
Now all right i hope.
