### ISSUE TITLE
Old posts able to be edited

### ISSUE THREAD

**Issue by seitbekir** [overtake/TelegramSwift#238]
I have channel and tried to edit post that was published few days ago and found that "edit" is available in context menu over post.
![image](https://user-images.githubusercontent.com/7370602/48969995-45bd2700-f00f-11e8-92e1-f4dfa4f95f21.png)
(18 ноября = November 18)

After I clicked it the post editing mode opened in textarea.
![image](https://user-images.githubusercontent.com/7370602/48970015-80bf5a80-f00f-11e8-8184-2b45d7c6623c.png)

But after I found that server declines all requests for editing post. Then I've checked Android version and there "edit" menu available only for last 24h posts. Seems, it is expected behavior, and plz skip that submenu for old posts.

**Comment by zweeltow** [comment]
Well, now you can edit post endlessly. C:
