### ISSUE TITLE
Notifications not in Notification Center and as banner

### ISSUE THREAD

**Issue by yochem** [overtake/TelegramSwift#239]
## Versions
macos: `10.14 (18A391)`
telegram: `4.6.1.143379 stable`

I don't receive notifications on my mac from telegram. The chats are not muted and the badge app icon works. My notifications for other apps (whatsapp, mail, etc) work fine.

Settings in app:
![in app](https://user-images.githubusercontent.com/23235841/49020053-d1f65800-f18f-11e8-8498-011413ec9751.png)

Settings in system preferences:
![system prefs](https://user-images.githubusercontent.com/23235841/49020088-ecc8cc80-f18f-11e8-81f1-0862ee7cd804.png)

**Comment by yochem** [comment]
thanks 🍻

**Comment by neongreen** [comment]
I hit the same bug. It went away after restarting macOS (not Telegram).
