### ISSUE TITLE
Missing search bar for gifs

### ISSUE THREAD

**Issue by lrose07** [overtake/TelegramSwift#24]
Telegram for MacOS does not have a search bar in the gifs sidebar menu.

TG for MacOS 3.4.106100 stable

**Comment by cryptochrome** [comment]
I can confirm. Same issue here.

**Comment by masc3d** [comment]
I can confirm it only loads the first batch of gifs when searching, but doesn't load more results when scrolling down, so the selection is rather limited. is that what you refer to @lrose07?

**Comment by lukejknight** [comment]
@masc3d, I believe he's referring to the fact that there is no search bar when opening the gif panel where stickers are, to search for gifs at all. However using @gif still allows you to search for gifs. 

See image (the bottom is the chat bar):

<img width="349" alt="screen shot 2018-02-08 at 7 34 32 pm" src="https://user-images.githubusercontent.com/6252715/35962896-27570100-0d07-11e8-91ea-1b6eead3a476.png">

**Comment by masc3d** [comment]
yes, but those are the recently used gifs. having a search bar there doesn't make much sense right.

**Comment by masc3d** [comment]
just checked against telegram desktop, and it does have a search bar so I suppose you're right. so this issue in addition to broken `@gif` which only loads the first few hits basically makes gifs rather unusable for this client.

**Comment by lukejknight** [comment]
@masc3d 

Glad you've found it, and yes, I was writing in comparison to Telegram Desktop. 

> broken @gif which only loads the first few hits

I don't experience this, unless by first few you mean around 15.

> having a search bar there doesn't make much sense right.

I disagree that it doesn't make sense in general, as it doesn't seem entirely intuitive to use @gif by itself to search gifs being a new user.

Speaking from experience having been a Telegram Desktop user for a while - I only learned you could do @gif after I asked a friend how to search for GIFs on macos version once I saw the search bar was missing. Maybe being a Telegram Desktop user biased my experience here, however I never saw any loud indication that @gif was a feature.

**Comment by overtake** [comment]
added to beta.
