### ISSUE TITLE
Newlines in messages are replaced with whitespaces

### ISSUE THREAD

**Issue by mchernyavsky** [overtake/TelegramSwift#240]
### Steps to reproduce

Send a message with the following content:

```
1
2

3


4
```

### Actual behaviour

All newlines in sent messages are replaced with whitespaces:

```
1 2  3   4
```

### Configuration
**Operating system:** macOS Mojave 10.14.1

**Version of Telegram Desktop:** 4.6.1.143379 Stable

**Used theme**: Dark Mojave

**Comment by revolter** [comment]
From what I saw, only pressing <kbd>ctrl</kbd> + <kbd>enter</kbd> has this behavior. Meaning, it puts the text on a separate line, but then sends it as a single line. <kbd>shift</kbd> / <kbd>alt</kbd> / <kbd>cmd</kbd> + <kbd>enter</kbd> are working correctly.

**Comment by overtake** [comment]
thanks guys. Reproduced and fixed. Also maybe we will fix it on server side (it means auto fix without client update)
