### ISSUE TITLE
FEATURE: Combine news from several groups or chats to one chat

### ISSUE THREAD

**Issue by radostnomne** [overtake/TelegramSwift#242]
My suggestion is combining messages (sorted by date) from different chats or groups to one chat. It will allow you to check news from groups you selected in one chat like as in social networks.

**Comment by zweeltow** [comment]
This suggestion for **Telegram**, not for **native Telegram for macOS**. 

You can write your suggestion in the Telegram Support in-app or in [website](https://telegram.org/support).
