### ISSUE TITLE
cannot see or at user in a group who's name manually set to "Deleted Account"

### ISSUE THREAD

**Issue by SteamedFish** [overtake/TelegramSwift#244]
A group member set its name manually to "Deleted Account" (but is not actually deleted)

Mac client cannot see this "Deleted Account" user in group member list.

Mac client cannot at this "Deleted Account" user, the popup doesn't list this user.

### Configuration
**Operating system:**

MacOS 10.14.1 (18B75)

**Version of Telegram:**
4.7.146563 stable

**Used theme**:

Dark Mojave

**Comment by overtake** [comment]
thanks. fixed. will be available in 4.8

**Comment by SteamedFish** [comment]
I still have this problem with Telegram 4.8.151307 stable.
Do I have to clear any cache to fix this issue?
