### ISSUE TITLE
Automatic Darkmode

### ISSUE THREAD

**Issue by dyedgreen** [overtake/TelegramSwift#251]
There should be a shedule option for the dark-mode, that enables it based on the system dark-mode status.

**Comment by dyumin** [comment]
![telegram 2019-01-20 17-05-19](https://user-images.githubusercontent.com/7953339/51440207-b57d2480-1cd5-11e9-9fa7-f2a046f19330.png)

**Comment by fenhl** [comment]
I am on macOS 10.12.6 Sierra and the app doesn't appear to have this toggle. Would it be possible to make it available for older systems? Dark Mode was introduced in macOS 10.10 Yosemite.
