### ISSUE TITLE
Telegram for macOS does not display poll.

### ISSUE THREAD

**Issue by onkarjit** [overtake/TelegramSwift#255]
When Polls came out on the iOS app I made one for my group. I have Telegram for macOS up to date. But the poll which I created on iOS before Telegram for macOS supported polls is being displayed as: 

> This message is not supported by your version of Telegram. Please update to the latest version from the AppStore or install it from https://macos.telegram.org.

How can I make Telegram for macOS show the poll?

**Comment by overtake** [comment]
what the version your macos application?

**Comment by onkarjit** [comment]
I'm the version Telegram 4.8.151695

**Comment by overtake** [comment]
can you contact me in telegram? t.me/vihor

**Comment by onkarjit** [comment]
Needed to relog.
