### ISSUE TITLE
Push newest code

### ISSUE THREAD

**Issue by blepc** [overtake/TelegramSwift#256]
This repo looks unmaintained

**Comment by HarukaMa** [comment]
@blepc don't hold any hope here, open-sourced telegram clients are completely joke (except Qt desktop version)

**Comment by blepc** [comment]
Looks like everything now builds properly, except for 2 submodules being outdated. Sparkle and Postbox need to point to master

**Comment by Hummer12007** [comment]
Bump @overtake

**Comment by overtake** [comment]
done

**Comment by 360fun** [comment]
new source code please! 🌳

**Comment by kathampy** [comment]
@overtake Please update the source. There are bugs I'd like to fix.

**Comment by overtake** [comment]
5.7 has pushed
