### ISSUE TITLE
Downloaded files with same name will not open correctly

### ISSUE THREAD

**Issue by xiamaz** [overtake/TelegramSwift#259]
Two different files with the same name and afterwards opening them will always open the first downloaded one.

**Expected behavior**

Both files should be shown correctly when clicked or a warning should be shown, when the users attempts to download the second file.

Telegram Version: 4.9.155353

**Comment by AbelToy** [comment]
I've also experienced this. Just to add some details:

A file named A.pdf is sent and downloaded. It opens properly. Later, another file named A.pdf is sent. When downloading, it's renamed to A (1).pdf. However, clicking on it will show a preview for the original A.pdf, instead of the new file.

**Comment by overtake** [comment]
fixed in latest releases
