### ISSUE TITLE
Telegram allows deleting seen messages

### ISSUE THREAD

**Issue by woj-tek** [overtake/TelegramSwift#26]
### Steps to reproduce
1. Receive a message from userA
2. *open* and *view* a message from userA
3. userA removes the message indicating that it should be removed for me as well

### Expected behaviour
userA must not be able to delete a message that has already been seen (I'm ok with removal of the messages before I've seen them)

### Actual behaviour
The message is completely removed! This causes quite a concern and is mind-boggling when you would think that you have seen the massage and look through recent ones yet you can't find it!

### Configuration
**Operating system: macOS HighSierra 10.13**
**Telegram version: 3.5.2.107976

I think this is an issue with telegram itself as it happens also in all tested telegram clients, see: 
* https://github.com/telegramdesktop/tdesktop/issues/4019
* https://github.com/zhukov/webogram/issues/1531
* https://github.com/overtake/TelegramSwift/issues/26

**Comment by longnd** [comment]
I think `this is a feature, not a bug`, but I agree that it should be handled in a more obvious way. Example: if a message hasn't been seen, it could be completely removed, if it was seen, it should be removed and replaced by a message like "this message was removed" so the user which seen it can know what happend. It would reduce the confusion as well.

**Comment by woj-tek** [comment]
@longnd WhatsApp has solved it this way and while I'm not really fond of WA this actually makes way more sense and greatly reduces the confusion.
