### ISSUE TITLE
Forget to push submodules?

### ISSUE THREAD

**Issue by Vanyoo** [overtake/TelegramSwift#263]
fatal: reference is not a tree: 096a7bde32619234f33178156e41ebf33277e7fc
fatal: reference is not a tree: 62ebdc6d9c61d57bd5a13a7f2db78805abed5175
Unable to checkout '096a7bde32619234f33178156e41ebf33277e7fc' in submodule path 'submodules/Postbox'
Unable to checkout '62ebdc6d9c61d57bd5a13a7f2db78805abed5175' in submodule path 'submodules/Sparkle'

**Comment by Vanyoo** [comment]
I followed repository's README file, using --recursive to clone . But GIT prints those words.

**Comment by bakl** [comment]
+1, Same problem

**Comment by overtake** [comment]
check again. fixed
