### ISSUE TITLE
Ctrl+Tab to switch chats acts weird

### ISSUE THREAD

**Issue by SijmenSchoon** [overtake/TelegramSwift#27]
Generally, using ctrl-tab and ctrl-shift-tab to switch between chats works just fine. However, this breaks in some cases.

One of these cases, and the only reproducible one I could find, is using ctrl-shift-tab on the first chat in the list, which will make it go to some random chat way down in the list, after which it seems to go in a totally random order.

**Comment by pinkisemils** [comment]
For me, it just randomly breaks after running the client for _some_ time. There is no definitive way I've found to trigger this, but the app will just stop responding to ctrl-tab and ctrl-shift-tab keystrokes. This is really painful.

**Comment by VitaliyR** [comment]
It is the end of 2018 - and still issue is present :(

**Comment by overtake** [comment]
sorry for that. i fixed it today.
