### ISSUE TITLE
Menu bar broken with latest Telegram releases

### ISSUE THREAD

**Issue by gamato** [overtake/TelegramSwift#270]
Telegram menu bar looks like this on my OS X 10.11.6:
```Telegram _NS:99.title _NS:77.title _NS:163.title```
I think it started with version 4.9.x and has been a pain since.

**Comment by gamato** [comment]
Please note that I use the app downloaded from the website, not from the App Store.

**Comment by overtake** [comment]
fixed

**Comment by gamato** [comment]
@overtake A few releases ago this issue appeared again. The text is slightly different (_NS:104.title ...). Do you need a new issue for fixing it, please? Thanks.

**Comment by AnyOfYou** [comment]
Have the same issue, menu bar title shown as "_NS:104.title, _NS:82.title, NS:168.title". macOS version 10.11.6. Telegram version 7.5.1 (213563). Should reopen this issue.

**Comment by pimenta** [comment]
Me too. Telegram 7.5.1 (213563) Stable and Telegram 7.5.1 (213565) Beta, Mac OS X 10.11.6, English US.

**Comment by jabohn** [comment]
Still broken in 7.6

**Comment by onemoarcherry** [comment]
still broken
