### ISSUE TITLE
Support MacOS Share Sheet

### ISSUE THREAD

**Issue by suyashcb** [overtake/TelegramSwift#274]
Love how well built the Telegram MacOS app is, but disappointed that it doesn't have share sheet support. This is awesome for sharing from the News app and Safari and one of my favorite features on Telegram for iOS.

**Comment by overtake** [comment]
supports for appstore version

**Comment by woj-tek** [comment]
This was already asked in #196 and issue was closed with same comment: "available in appstore version" without explanation whether it's possible to enable it in non-appstore version. What's more, download link (https://macos.telegram.org) emphasises *NON* appstore version so it would be nice to have feature parity in that version as well.

I read:
* https://developer.apple.com/app-extensions/
* https://developer.apple.com/design/human-interface-guidelines/macos/extensions/share-extensions/
* https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Share.html
* https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/index.html#//apple_ref/doc/uid/TP40014214-CH20-SW3

And none of them mentions requirement for AppStore. The last link mentions:
> The best way to start developing an app extension is to use one of the templates that Xcode provides for each extension point on both platforms. Each template includes extension point–specific implementation files and settings, and produces a separate binary that gets added to your containing app’s bundle.
> To distribute app extensions to users, you submit a containing app to the App Store. When a user installs your containing app, the extensions it contains are also installed.

But it hardly seems like a hard requirement - rather a convenience to distribute those extensions...

**Comment by overtake** [comment]
@woj-tek You right. Finally I have implemented it for alpha and beta and hope will be available in next release (5.7)
