### ISSUE TITLE
[bug] gifs-menu duplicate my gifs

### ISSUE THREAD

**Issue by zxzzz8** [overtake/TelegramSwift#276]
![Screen Shot 2019-03-13 at 17;22;24](https://user-images.githubusercontent.com/20977838/54291273-fea27400-45b4-11e9-9ea8-998e0d68a695.png)

after one of the resent updates, every time i switch to the gifs menu, it adds one copy of all my gifs list....
if i send a gif [what changes the order] and then re enter, the new clone have the new order, but older clones stay w there old order.... [same w adding a new gif to the list].

all the clones reset after a restart, but that doesn't prevent from new clones to start showing again....

**Comment by overtake** [comment]
Sorry for that. i already fixed it in beta. will release soon.

**Comment by zxzzz8** [comment]
thank you ^^
