### ISSUE TITLE
[Bug] Empty window in a while after hiding/minimizing to dock

### ISSUE THREAD

**Issue by evxn** [overtake/TelegramSwift#282]
After the last update I'm getting empty screen in a while after hiding/minimizing the app. Have to relaunch it every time.

Mac OS 10.14.4 (18E226)
App: `5.0 (164585) AppStore`
![Screen Shot 2019-03-28 at 3 22 16 PM](https://user-images.githubusercontent.com/134564/55157629-f37f4480-516d-11e9-9c2a-73f501fab228.png)

If you'll help me to debug it I can bring more info.

**Comment by overtake** [comment]
telegram @vihor. please contact.
