### ISSUE TITLE
Unable to add new profile photo

### ISSUE THREAD

**Issue by diedummydie** [overtake/TelegramSwift#287]
Telegram version: 5.0.1 (164832) AppStore
macOS version: 10.14.1 Mojave

When I try to add a new profile photo, I can select a .jpg or .png image and see it in the crop interface.

![crop interface](https://user-images.githubusercontent.com/1759544/55598044-ae838100-571e-11e9-8ef4-6a9a132ed1c9.png)

When I click 'Done' there, it behaves as if I had clicked 'Cancel', taking me back to the edit profile form. When I had an older photo there, it showed that photo next to my name. I tried again after removing the old photo, and now it just shows my initials as an auto-generated 'photo'.

![edit profile](https://user-images.githubusercontent.com/1759544/55598143-3e292f80-571f-11e9-867c-ef9005e11969.png)

The 'Done' button on that edit profile form is never highlighted or clickable unless I've changed the text. Trying to add a photo while that 'Done' button is clickable has no effect. Again, the 'Done' button is clickable in the crop/rotate interface, but it behaves like a cancel button.

I've tried an rgb .png, a progressive .jpg, and a baseline .jpg. I've restarted both Telegram and macOS. 

If you can't reproduce this and don't have a fix, I don't mind, just close the issue. I just thought I'd mention it in case it affects the current build for everyone, not just me.

**Comment by diedummydie** [comment]
Oh, I also tried adjusting the crop frame to see if letting Telegram create its own version of the image helps. It doesn't.

**Comment by zweeltow** [comment]
What about latest versions? I think this has been fixed.
