### ISSUE TITLE
No preference to customize date displays

### ISSUE THREAD

**Issue by danielhoherd** [overtake/TelegramSwift#289]
As of Telegram.app version 5.1 (166482) AppStore the dates displayed are confusing. For example, in my contact list I see people with "last seen" entries like "11.12.18", "3.04.19", "19.03.19".

A simple (as in making an app that is easy to use) fix would be to respect MacOS System Preferences -> Language and Preferences. In here you can select how certain pieces of information will be represented. Such as, M/D/YY for dates in USA.

A more complicated (as in allowing a higher level of customization within the app) fix would be to allow a custom date format (eg: `%F %T%z` for rfc-3339) , or a drop-down with common date formats.

**Comment by s0ph0s-2** [comment]
I'm not sure I can imagine a scenario in which I'd want Telegram to use a different date format than the one I've configured in System Preferences.

**Comment by landry314** [comment]
looks like they just fixed this for the other telegram for macos:

https://github.com/telegramdesktop/tdesktop/pull/17068

**Comment by landry314** [comment]
This is really a pain for me to see the date the wrong way with only numbers. I am always checking last seen times and this confuses me all the time.

I personally would like to see the month written as "May", "Jun", "Oct" and then the day as a number. It is more natural to read dates that way, but just adhering to the system settings is enough. The region set in system should determine this.

**Comment by danielhoherd** [comment]
FWIW this is no longer a problem for me. I just tested it by going into "Language & Region" prefs and enabling 24 hour time, then restarting Telegram. I saw times in the app show up as 24h.

**Comment by landry314** [comment]
but this isnt your initial problem or the title of this issue.

**Comment by danielhoherd** [comment]
@landry314 From the original description:

> A simple (as in making an app that is easy to use) fix would be to respect MacOS System Preferences -> Language and Preferences.

I have not confirmed that the app allows customization beyond that, but macos 12 does allow you to customize localization per-app, so that is worth investigating.
