### ISSUE TITLE
Hidden on Start doesn't work

### ISSUE THREAD

**Issue by CoolTomatos** [overtake/TelegramSwift#290]
A few updates ago, I believe before 5.0, hidden on start worked. But now it doesn't.

My current telegram version is 5.1 (166481) Stable.
My MacBook is running 10.14.4.

**Comment by dwhagar** [comment]
I am experiencing this as well.  Normally one can tell macOS to hide a window on start.  This does not work as expected.
6.2.3 (202354) Stable
Macbook Pro 13" 2017 running macOS 10.15.5
