### ISSUE TITLE
[Feature Request] Filter from Calls Tab Channels, Groups, Bots, Chats

### ISSUE THREAD

**Issue by ioemilio** [overtake/TelegramSwift#301]
I think Telegram client needs some sort of filter for the chat type, allowing users to switch the view from the list of all chats to a view on only specific types of chats (e.g., when I scroll I just want to see groups; when I scroll I just want to see channels; etc).
In fact, when in the Calls Tab, it is not easy to find the right group, channel, bot, or chat while scrolling down. Looking for a specific chat is now only possible by scrolling among all chats or by using the search feature.
Other than another way to look for a specific chat, this would give users an easy way to control what channels they subscribed or bot they are using.

**Comment by 360fun** [comment]
It has been recently implemented as "developer option" in the latest stable release! ;)

![image](https://user-images.githubusercontent.com/844090/75265737-9c587880-57f1-11ea-9353-5c265e05c207.png)

https://t.me/tgbeta/3976

![image](https://user-images.githubusercontent.com/844090/75265670-864ab800-57f1-11ea-9eac-de7af9769953.png)
https://t.me/tgbeta/3997

**Comment by ioemilio** [comment]
This is great! 👍 👍 👍
