### ISSUE TITLE
The bot information in the group is always written 'has no access to messages'

### ISSUE THREAD

**Issue by topazbarziv** [overtake/TelegramSwift#308]
When there is a bot in the group and it is a admin, a telegram (macOS) always wrote 'no access to messages' but in Telegram (android) writes 'has access to messages'.
The mistake is in macOS.

MacOS:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/18365476/57275368-09562280-70a7-11e9-98b4-b5d662493a6a.png">

Android:
![IMAGE 2019-05-07 09:05:27](https://user-images.githubusercontent.com/18365476/57275443-428e9280-70a7-11e9-9abe-4b12cc6e2a28.jpg)

**Comment by zweeltow** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/50041341/82679762-08614600-9c54-11ea-98d6-69ada7fb8a58.png)
