### ISSUE TITLE
Give Telegram a more native macOS look?

### ISSUE THREAD

**Issue by eivindml** [overtake/TelegramSwift#31]
One thing that I would like to see would be to give the app an even more native look and feel, to signify even more that this is a native app. Maybe take some inspiration from Messages.app.

- Add VisualEffectView to the contact list view, so it's a bit more transparent and vibrant. 
- Remove the bar on top of the window. 
- Style the input field to look more native.

Just some thoughts for how I think this awesome application could be even better. :)

<img width="1608" alt="screen shot 2017-11-07 at 09 27 22" src="https://user-images.githubusercontent.com/202450/32484377-d7bdd818-c39f-11e7-9ae6-e4d9a5cd4887.png">

**Comment by tudemon** [comment]
Disagree. Telegram for MacOS has the most beautiful UI I have ever seen. Please don't make changes

**Comment by bastones** [comment]
Well if it's not too much trouble it would be nice to have both UIs available to switch between within the app settings to satisfy both groups, as I also support the idea of having a more native look-and-feel - one that follows Apple's design guidelines for macOS apps.

**Comment by alistairharris** [comment]
I agree with @bastones, but if push comes to shove (and so as to keep a tighter codebase), I'd rather following Apple's design guidelines over the current UI.

**Comment by onkarjit** [comment]
I prefer the current UI, please don't remove it.
