### ISSUE TITLE
Help page on telegramswift keyboard shortcuts

### ISSUE THREAD

**Issue by maxim-uvarov** [overtake/TelegramSwift#311]
Hello! It seems like there is no single page or post in the official channel, that describe all the keyboard shortcuts of TelegramSwift. Or I couldn't find it. So I suggest to create one and if it exists - to put the link on it somewhere close to the final user.

**Comment by zweeltow** [comment]
Now you can check the shortcuts https://github.com/overtake/TelegramSwift/wiki!

And also shortcuts show in-app: **Settings > General > Keyboard Shortcuts**.
