### ISSUE TITLE
[BUG] Telegram crashes and all chats are missing

### ISSUE THREAD

**Issue by gamato** [overtake/TelegramSwift#313]
Since update to version 5.2 Telegram has been crashing a few times a day. Occassionally it fails to start and displays a message "Something is wrong" (or something like that). Just now I updated to the latest hotfix release (5.2.2 (170992) Stable on El Capitan) and after restart of Telegram all my chats are gone. All I see is Saved messages chat. This is really bad. What now ?!?

**Comment by gamato** [comment]
Btw, I've got a feeling Telegram lacks a proper testing in recent months. I've hit quite a few glaring issues that should have been spotted right away before releasing the app to public. I also try to advertise Telegram among my friends and family -- and such issues are really not helping the case.

**Comment by zweeltow** [comment]
Well i hope on latest versions you don't have some problems.
