### ISSUE TITLE
Timestamps are broken after last update

### ISSUE THREAD

**Issue by printercu** [overtake/TelegramSwift#32]
Hi!

After last update all timestamps are replaced with day of week:
![image](https://user-images.githubusercontent.com/1144890/32768751-34e21808-c92a-11e7-9a5d-c6316020490b.png)

**Comment by overtake** [comment]
why broken?

**Comment by printercu** [comment]
Ah, now I see, that it shows time of day :) But only for today messages. All messages missed time labels because I had no new messages today when posted an issue.

I still can't find time of day for old messages neither when selecting them nor in context menu. Am I missing some setting for this? While is shown in tooltip on the top of chat, maybe it's better to show time in the labels on the right?

**Comment by overtake** [comment]
hover on date.
