### ISSUE TITLE
How to remove abandoned data from Mac client after uninstallation? Where are they stored?

### ISSUE THREAD

**Issue by itinance** [overtake/TelegramSwift#325]
After uninstallation of Telegram client, some data like my Mobile number are still stored somewhere on my machine.

I have tried to find the location in

```
~/Library/Caches
~/Library/Application Support
Keychain
```

No chance. But when I reinstall the application, it still knows my Mobile number.
Proof:

Across reinstallation my mobile number is still known to the application:
<img width="330" alt="Screenshot 2019-07-12 09 03 58 copy" src="https://user-images.githubusercontent.com/1758597/61113330-56cb8300-a48e-11e9-9f56-bfd6e978ac67.png">

How to remove those data? Where are they located?

**Comment by itinance** [comment]
Any news on this?

**Comment by gagarine** [comment]
Certainly in ~/Library/Group Containers/.keepcoder.Telegram 

You may also may have a lot of data (cache) inside this folder. See https://github.com/overtake/TelegramSwift/issues/331

**Comment by itinance** [comment]
Thanks for the Hint, @gagarine. There is no .keepcoder.Telegram folder, but I have found a folder called "6Nxxxxx.ru.keepcoder.Telegram" in `~/Library/Group Containers`.

Removing this folder enabled me to reinstall the application with my phone number receiving the code. Many thanks!
