### ISSUE TITLE
Telegram window becomes empty when moved to another display.

### ISSUE THREAD

**Issue by ksvintsov** [overtake/TelegramSwift#328]
When I move telegram window from one display (for example, Macbook builtin display) to another one (external display), window becomes empty(see screenshot). If I move window back, it becomes OK.
![Screen Shot 2019-07-18 at 18 54 18](https://user-images.githubusercontent.com/2383283/61455751-a8907380-a98e-11e9-86bd-e612f17a164e.png)

**Comment by overtake** [comment]
App version?

**Comment by ksvintsov** [comment]
Telegram version 1.7.14

**Comment by ksvintsov** [comment]
Correction.
It happens if telegram was started when external display is not plugged in. So, to reproduce:
1) Quit telegram desktop if it is started

**Comment by overtake** [comment]
You speaking about desktop. This repository for macos native client. I suggest to use it: macos.telegram.org
