### ISSUE TITLE
Animated stickers does not animated

### ISSUE THREAD

**Issue by korenskoy** [overtake/TelegramSwift#332]
Stickers are not animated on both non-appstore versions  (stable and beta). 
Only first frame of a animation is shown.

OSX 10.13.6 (17G7024)
Telegram: 5.5.1 (176730) Beta

How can I help you find the problem?

**Comment by overtake** [comment]
Hi. I have fixed it in beta. Please wait new release

**Comment by korenskoy** [comment]
Now it's work! Thank you!
