### ISSUE TITLE
TouchBar missed localisation labels (EN!)

### ISSUE THREAD

**Issue by fzzr-** [overtake/TelegramSwift#336]
- TG version: [5.5.1 (176369) AppStore](https://apps.apple.com/us/app/telegram/id747648890) ([screenshot](https://user-images.githubusercontent.com/888526/62768684-0f8ddd80-baa0-11e9-8280-211bfe3dd43f.png)).
- MacOS version: 10.14.6 (18G87).
    - locale: EN

Steps to repro:
1. View / Customise Touch Bar ([screenshot](https://user-images.githubusercontent.com/888526/62768949-a8245d80-baa0-11e9-9d59-9e4af314fc32.png))
2. Lets see plugs in prod! 👇
![result screenshot](https://user-images.githubusercontent.com/888526/62769004-ca1de000-baa0-11e9-8e60-a2e18797c484.png)

**Comment by overtake** [comment]
Thanks. Fixed in betas
