### ISSUE TITLE
icons in bottom of window missing

### ISSUE THREAD

**Issue by MKesenheimer** [overtake/TelegramSwift#338]
<img width="626" alt="icons" src="https://user-images.githubusercontent.com/1159298/63026987-6cc4cd00-beac-11e9-8fd6-7c9d79c2fe79.png">

After I updated from version 4 to version 5 of Telegram for macOS, the icons disappeared at the bottom of the window (see image).

I am on OS X 10.11.6 (El Capitan), Macbook pro mid 2014.

**Comment by overtake** [comment]
fixed
