### ISSUE TITLE
Lottie.framework not found

### ISSUE THREAD

**Issue by parsanoori** [overtake/TelegramSwift#342]
When I try running telegram it says that:

`error: ~/Library/Developer/Xcode/DerivedData/Telegram-Mac-gwurtqhplwvqvkfhdpflsikvveyl/Build/Products/DebugAppStore/Lottie.framework: No such file or directory`

And while cloning I got this problem which I think it's the main cause of the above error:

`Fetched in submodule path 'submodules/lottie-ios', but it did not contain 3460ebfa57c4178c2f7cbff9cc67dd689b0c5e70. Direct fetching of that commit failed.`

**Comment by rogerchina** [comment]
me too

**Comment by parsanoori** [comment]
Maybe I've found the solution!
Update your xcode to xcode 10.3 so it can support Swift 5 and manually download lottie and import it to the project.

**Comment by Scvairy** [comment]
Added `git@github.com:airbnb/lottie-ios.git` through Swift Package Manager, branch `lottie/macos-spm`

https://github.com/airbnb/lottie-ios#adding-it-to-an-existent-ios-project-via-swift-package-manager

And added Lottie to frameworks in Telegram project.

**Comment by overtake** [comment]
I have already removed lottie framework.
