### ISSUE TITLE
OS-independent dark/light theme option gone

### ISSUE THREAD

**Issue by Palivonas** [overtake/TelegramSwift#348]
Issue: not possible to switch Telegram to a dark theme anymore, without switching the whole MacOS to dark mode.

Until some version, it was possible to just toggle dark/light themes in Telegram independently of OS settings. Can it please be brought back? With three options this time, I suppose:
* Honor OS theme (default option)
* Dark (despite what is set in OS)
* Light (despite what is set in OS)

Or something similar (different variations within dark/light themes needs to be incorporated as well I guess)

Why: it's great great having apps in dark mode when they have proper support for it (like Telegram), but OS-wide dark mode is not a desirable option for everyone (including me).

**Comment by overtake** [comment]
Weird. Try to switch off toggle in appearance settings “follow system
appearance”

**Comment by Palivonas** [comment]
I haven't considered the possibility of being blind, but maybe I am. Thanks for the _Swift_ reply and for maintaining this!
