### ISSUE TITLE
Add a setting to disable sticker/emoji animation or to run it only once

### ISSUE THREAD

**Issue by slevir** [overtake/TelegramSwift#349]
Some other official clients (or maybe all of them, I don't know) have already implemented this, so it'd be nice to see on macos as well

**Comment by zweeltow** [comment]
**Settings > Stickers > Loop Animated Stickers**.

![image](https://user-images.githubusercontent.com/50041341/82848169-14bafc80-9efb-11ea-9f2f-2bcdde9c72a8.png)
