### ISSUE TITLE
Cannot send messages to one person only from macOS app

### ISSUE THREAD

**Issue by nikitavoloboev** [overtake/TelegramSwift#35]
Whenever I send any photo or document to that person, it just shows this : 
 
![2017-11-21 at 16 27](https://user-images.githubusercontent.com/6391776/33080609-da37ea54-ced8-11e7-9e5b-ae6e08d743e4.png)

But never completes.

The problem is only with this one contact as everything works well on other contacts. And this problem is only there when sending photos / files from macOS Telegram app. If I send things to this person either from web or from my phone or from `Telegram Desktop` app, everything works.

What should I do? Thank you.

**Comment by Lozik** [comment]
Same issue over here. I'd like to add that the same happens while sending voice messages.
In the Telegram macOS chat on telegram (https://t.me/macswift) there seem to be other people who have the same issue, too.

**Comment by nikitavoloboev** [comment]
Logging out and in solved this for me on mac.

**Comment by Lozik** [comment]
Effectively, thanks for the feedback! It does for me too!
