### ISSUE TITLE
Why can I access it via sockt5 in the shell and telegram can't?

### ISSUE THREAD

**Issue by StringKe** [overtake/TelegramSwift#353]
![image](https://user-images.githubusercontent.com/31089228/65401400-7110ce00-ddfa-11e9-987c-fc6dfcf93b5c.png)

My network environment is more complicated. I created http and sockt5 agents locally through special methods, which can be used normally in the terminal and browser, but tg cannot use sockt5.

**Comment by ArnoFrost** [comment]
Me too.
Even I use mtproto it still can't connect... Is there anything special setting on the MacOS?
