### ISSUE TITLE
Off-by one error in message replies

### ISSUE THREAD

**Issue by ergl** [overtake/TelegramSwift#358]
Clicking on the quoted message reply will scroll and highlight an incorrect message, always one or two messages below the expected message. This happens both on your own messages and with messages from other people.

Version: 5.7 (181196) Stable
macOS 10.14.6

![](https://www.dropbox.com/s/c9k5ddo5hgxk0p0/telegram.gif?raw=1)

**Comment by overtake** [comment]
Hi. Sorry about that. I have already fixed it in beta. Please wait next
stable release (approximately tomorrow)

**Comment by ergl** [comment]
That's great to hear, thanks for the quick reply!

**Comment by ergl** [comment]
Can no longer reproduce as of 5.8 (184898) Stable. Thanks!
