### ISSUE TITLE
Telegram 5.8 is completely broken -- no controls, no chats, nothing

### ISSUE THREAD

**Issue by gamato** [overtake/TelegramSwift#361]
I've just received a notification about new version of Telegram and I clicked on Update. What a crazy idea. After update and relaunch all I see is empty white space with a few misplaced icons, no controls, no chats, nothing at all. What a pain.

And since this is yet another broken release I've encountered in recent months, and most seriously broken one, I'm not sure what to think about the testing and release process of this application. Telegram is a very important tool for many of us and there's no place for such missteps. Please think about it. Thanks.

[Telegram 5.8 (184898) Stable on OS X 10.11.6]

**Comment by overtake** [comment]
Try to update to latest stable version. I’ve fixed bugs on 10.11

**Comment by gamato** [comment]
It works now. Many thanks.
