### ISSUE TITLE
Search list does not disappear when clicking the search icon again

### ISSUE THREAD

**Issue by hex86** [overtake/TelegramSwift#362]
When searching for a text in a group chat or in a private chat, the result list appears and does not disappear correctly when i click on the search icon again.

The list just stick there and can't be removed unless i enter another chat.

Clicking on the stuck list has no effects, and it does not resize when resizing the app.

![issue](https://user-images.githubusercontent.com/52679507/67345280-2ee6c380-f543-11e9-81e4-ab3bf44db8ca.gif)

**Comment by zweeltow** [comment]
Fixed.
