### ISSUE TITLE
v5.8 Color Theme always goes back to tinted blue

### ISSUE THREAD

**Issue by filippoferrari** [overtake/TelegramSwift#363]
With the latest update from the Mac App Store after about a minute the color theme switches back to tinted blue, no matter which theme is selected.

**Comment by artemsmikh** [comment]
Can confirm. Happens only when auto night mode is enabled though.

**Comment by filippoferrari** [comment]
Mine was set on system. I have now disabled it and it does not seem to switch color theme anymore.

**Comment by overtake** [comment]
Sorry, but this is not a bug. just disable your auto night mode settings

**Comment by artemsmikh** [comment]
But what if we'd like to leave this option turned on?

**Comment by overtake** [comment]
Leave it. There is no problem. But what you want if your system theme is dark. Of coruse app automatically switches back to dark theme which is selected in auto-night mode.

**Comment by artemsmikh** [comment]
@overtake The problem is that there are 2 dark themes in the latest version: 'tinted blue' and 'system' and we assume that if you select 'system' as a preferred dark theme it won't switch back to 'tinted blue' (as it is doing now).

**Comment by overtake** [comment]
i've changed the behaviour.
