### ISSUE TITLE
Telegram keeps crashing after recent updates

### ISSUE THREAD

**Issue by ArtemZ** [overtake/TelegramSwift#364]
Hello,
After the recent updates (delivered 10/24 ?) my telegram client is unable to launch normally, it crashes immediately, offers to restart it and provides error details I'm attaching.

[telegram_crash.log](https://github.com/overtake/TelegramSwift/files/3769559/telegram_crash.log)

**Comment by overtake** [comment]
hi. can you contact me with telegram? t.me/vihor

пт, 25 окт. 2019 г. в 01:32, Artem Zhirkov <notifications@github.com>:

**Comment by donnywdavis** [comment]
I'm having the same issue. The problem reporter window that pops up for me says that it can't find a file in `/Users/keepcoder/Dropbox/Telegram-multi-acc/Telegram-Mac/`. The specific message is `Fatal error: Cannot use bindings. Application context is not exists: file /Users/keepcoder/Dropbox/Telegram-multi-acc/Telegram-Mac/ApplicationContext.swift, line 197`

**Comment by ArtemZ** [comment]
After the recent update the issue not repeats again

**Comment by overtake** [comment]
beta?

**Comment by overtake** [comment]
> After the recent update the issue not repeats again

Ah, yes. your crash was connected with swift complier.  I switched back to 10.3 and everything is ok now =)
