### ISSUE TITLE
Can't click link in some scence

### ISSUE THREAD

**Issue by github-yxb** [overtake/TelegramSwift#365]
Like:
![image](https://user-images.githubusercontent.com/7059300/67658570-f0169a80-f994-11e9-88fd-5a2c92418c4b.png)
But on telegram web version or pc version,  after click link can pop panel on bottom  :
![image](https://user-images.githubusercontent.com/7059300/67658659-2bb16480-f995-11e9-8605-b8befc3ee49a.png)

**Comment by overtake** [comment]
looks like web version. 
I suppose this problem related to the https://github.com/zhukov/webogram

**Comment by github-yxb** [comment]
> looks like web version.
> I suppose this problem related to the https://github.com/zhukov/webogram

First image is telegram macos swift version, not web version:
![image](https://user-images.githubusercontent.com/7059300/67665728-4ab7f280-f9a5-11e9-9eea-bf9736d71bec.png)

Second image is web version,no problem.

**Comment by zweeltow** [comment]
What about latest versions?

**Comment by github-yxb** [comment]
> What about latest versions?

fixed
