### ISSUE TITLE
Telegram has blocked a chat for me

### ISSUE THREAD

**Issue by vpapidokha** [overtake/TelegramSwift#368]
Hello,
Have an issue on macOS and iOS devices that telegram chat was blocked for me due to porn content in it. However, I still can access it from web version and other people from it freely using it from Windows and Android devices. Could you help me?

Invite link to the chat:
https://t.me/ukrcomicschat 

I'm from Ukraine, that's jus in case if It's relative to this issue in other versions of Telegram:
https://github.com/telegramdesktop/tdesktop/issues/6224

![IMG_096F81332438-1](https://user-images.githubusercontent.com/20145156/67927668-db6b1a00-fbc1-11e9-9749-19425f532d7e.jpeg)
<img width="580" alt="Screenshot 2019-10-30 at 15 35 22" src="https://user-images.githubusercontent.com/20145156/67927673-e1f99180-fbc1-11e9-8ff7-6d9325de4127.png">

**Comment by zweeltow** [comment]
Use version from https://macos.telegram.org.
