### ISSUE TITLE
Telegram macOS v5.8 can't connect to localhost socks5 proxy

### ISSUE THREAD

**Issue by Loyalsoldier** [overtake/TelegramSwift#370]
Wired thing happens.
My socks5 proxy is okay running on `127.0.0.1:1080`
Telegram v5.8 can't connect to that socks5 proxy on macOS Catalina 15.1, neither Mac App Store version nor direct downloaded version from https://macos.telegram.org. But works fine on macOS Mojave 14.5

![Xnip2019-11-06_19-11-40](https://user-images.githubusercontent.com/10487845/68293759-9c5d2d00-00c9-11ea-8f8a-d1a9d9511443.jpg)

**Comment by tigerruanyifan** [comment]
also have that problem

**Comment by A1saka** [comment]
same issue. you got any idea of that?

**Comment by akram** [comment]
it works for me on a Telegram 5.7, and localhost:8080 socks proxy.

**Comment by h2cone** [comment]
I have the same problem.

**Comment by BlockDoveYoung** [comment]
same problem 
telegram 5.9.1 (189475) Stable

**Comment by fallenlord** [comment]
same problem for 5.9.1 (189475) Stable

**Comment by BlockDoveYoung** [comment]
> same problem
> telegram 5.9.1 (189475) Stable

1. delete everything about telegram
2. reinstall tg
3. add proxy
4. quit tg
5. start tg
6. waiiiiiiiiiiiit

it works for me

**Comment by fallenlord** [comment]
> > same problem
> > telegram 5.9.1 (189475) Stable
> 
> 1. delete everything about telegram
> 2. reinstall tg
> 3. add proxy
> 4. quit tg
> 5. start tg
> 6. waiiiiiiiiiiiit
> 
> it works for me

Thanks, it works for me too!

In my case, it's no need to delete and reinstall, but only:

1. add proxy
2. quit tg
3. start tg

and everything works fine!

**Comment by adolphinvx** [comment]
same problem, thanks to @fallenlord , restart just works.

**Comment by wyh** [comment]
Add the proxy, then go to restart telegram works. 

Please help fix this bug, a blocker for new  users. 

Actually it costs me days to found the solution, since mac app usually do not need to restart.

**Comment by yedong2010** [comment]
Should download the Telegram Desktop version, the desktop version of the local proxy without any problems

**Comment by Achillesxu** [comment]
add proxy, 
and restart it,
reopen tg,  
scan the login qr using phone app,
finally successfully login

**Comment by liuxhit** [comment]
restart telegram(v6.3.1 (203760) Stable) works for me

**Comment by dragonbbc** [comment]
> @BlockDoveYoung Thanks, it works for me too!
> 
> In my case, it's no need to delete and reinstall, but only:
> 
> 1. add proxy
> 2. quit tg
> 3. start tg
> 
> and everything works fine!

works for me too.

**Comment by jdhao** [comment]
> @BlockDoveYoung Thanks, it works for me too!
> 
> In my case, it's no need to delete and reinstall, but only:
> 
> 1. add proxy
> 2. quit tg
> 3. start tg
> 
> and everything works fine!

Works for me, thanks! I wonder why this issue has not been fixed in such a long time....

**Comment by jiangxiaoqiang** [comment]
same issue

**Comment by jiacai2050** [comment]
@Loyalsoldier Could you reopen this issue? although it will works after reopen Telegram, it broken at the first time

**Comment by fwx5618177** [comment]
Just need to do 4 steps:
1. Installed TG.
2. Add Proxy and open Proxy.
3. Quit TG.
4. Re-open TG.
 Last, you would log successfully.

**Comment by CharryLee0426** [comment]
I had the same problem. And I solved it by these steps:

**Comment by AmirTalebi** [comment]
add telegram ip to firewall whitelist on socks5 server

**Comment by iliafaramarzpour** [comment]
> Wired thing happens. My socks5 proxy is okay running on `127.0.0.1:1080` Telegram v5.8 can't connect to that socks5 proxy on macOS Catalina 15.1, neither Mac App Store version nor direct downloaded version from https://macos.telegram.org. But works fine on macOS Mojave 14.5
> 
> ![Xnip2019-11-06_19-11-40](https://user-images.githubusercontent.com/10487845/68293759-9c5d2d00-00c9-11ea-8f8a-d1a9d9511443.jpg)

nice work, it works for me.

**Comment by wandererkin** [comment]
我的也是这个问题，为什么把issus给关了？

**Comment by QUARKER33** [comment]
> > same problem
> > telegram 5.9.1 (189475) Stable
> 
> 1. delete everything about telegram
> 2. reinstall tg
> 3. add proxy
> 4. quit tg
> 5. start tg
> 6. waiiiiiiiiiiiit
> 
> it works for me

must be restarted,works for me lol
