### ISSUE TITLE
my channel banned can you help my ? 

### ISSUE THREAD

**Issue by zetatechi** [overtake/TelegramSwift#395]
I had a channel with 80K members for 4 years. Telegram has banned it without a single warning. It's not fair because we didn't do anything wrong during these 4 years.

which is not related to terrorism, not related to sex , not related to spam! not related to child porn , not related to Annoyance for the telegram
![image](https://user-images.githubusercontent.com/60185719/72907122-9bdb4680-3d48-11ea-9fe3-e19240c8febc.png)

**Comment by Scvairy** [comment]
Try write to support@telegram.org
