### ISSUE TITLE
Последний апдейт ломает анимированные стикеры

### ISSUE THREAD

**Issue by zerezhka** [overtake/TelegramSwift#398]
<img width="506" alt="Screenshot 2020-01-24 at 14 17 29" src="https://user-images.githubusercontent.com/10316435/73054381-78cda580-3eb4-11ea-8b59-de5948885aa7.png">

5.9 (189446) Stable

**Comment by overtake** [comment]
![image](https://user-images.githubusercontent.com/1260850/73054483-ffc65200-3ea3-11ea-9e46-fb7980712eb1.png)
А гляньте эти настройки

**Comment by zerezhka** [comment]
помогло. раньше луп был по умолчанию, я подумал, что разломалось
