### ISSUE TITLE
menu bar titles gone

### ISSUE THREAD

**Issue by yochem** [overtake/TelegramSwift#4]
## versions and stuff
Macbook Air 13 inch
macOS Sierra v10.12.4
Telegram Desktop v3.4.106200 Stable
Language: Dutch

## Screenshot
![screenshot of the problem](https://user-images.githubusercontent.com/23235841/31496661-941ea224-af5c-11e7-88c1-c3e1a454bf77.png)

Tried restarting the Telegram app but that didn't work.

**Comment by overtake** [comment]
check now?

**Comment by yochem** [comment]
It works! What did you do to solve it?

**Comment by overtake** [comment]
magic :D
