### ISSUE TITLE
Version 3.5 offers update to non-existing version 3.6

### ISSUE THREAD

**Issue by magicgoose** [overtake/TelegramSwift#40]
![screen shot 2017-11-25 at 12 02 42 pm](https://user-images.githubusercontent.com/1442206/33229571-c9569ab0-d1d9-11e7-967f-7e4b4f096442.png)

3.6 is not mentioned in version history on the official page https://macos.telegram.org/

Also, for some reason the current download link at the website points at 3.5 instead of 3.5.3.

**Comment by overtake** [comment]
fixed.
