### ISSUE TITLE
Schedule message time selection

### ISSUE THREAD

**Issue by trollfred** [overtake/TelegramSwift#404]
![image](https://user-images.githubusercontent.com/3583824/73615677-679a3c80-460a-11ea-972f-5f7ee955038a.png)
Seriously???

**Comment by zweeltow** [comment]
Fixed on last versions. :)

![image](https://user-images.githubusercontent.com/50041341/82249675-e82f3f80-9952-11ea-82dc-9ed16b5c3fa2.png)
