### ISSUE TITLE
When selecting text the app freezes

### ISSUE THREAD

**Issue by Teivaz** [overtake/TelegramSwift#406]
When selecting text the app freezes.
Repro steps:
- Start select a text from a message from the beginning
- Before reaching the end stop, press and hold shift
- Release the pointer button
- Click after the last symbol in the text message

The application is left in an unresponsive state.

![telegram-bug](https://user-images.githubusercontent.com/4460981/73949266-7cbce700-48fa-11ea-911a-f77284d90b24.gif)

Telegram Version:
5.9.1 (189475) Stable

System:
macOS Catalina
Version 10.15.2
MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by overtake** [comment]
fixed. thanks
