### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by pniedzwiedzinski** [overtake/TelegramSwift#408]
Where can I look up key shortcuts for the app?

BTW love this ❤! It looks great and works smooth

**Comment by kozemirov** [comment]
Disappeared shortcuts(it was in 5.9.1 (190261)):
⌘ + control + digits — among filters
⌘ + digits — among conversations

Like here:
![Screen Shot 2020-02-18 at 15 23 28](https://user-images.githubusercontent.com/7889909/74735893-a5ca6980-5262-11ea-97a3-0360e6820b63.png)

**Comment by pniedzwiedzinski** [comment]
Maybe it should be in the docs? I
For my experience I know that there are more shortcuts like i.e Command+K.

Table with all shortcuts might be useful for newcomers

**Comment by pniedzwiedzinski** [comment]
Here is what I know:

- `Command`+`k` - opens search box anywhere
- `Command`+`←`/`→` - move backs and forwards
- `Command`+`f` - search in chat

- `Command`+`i` - focus to message input box
- `Command`+`↑`/`↓` - reply to message
- `Alt`+`↑` - edit your last message.

**Comment by zweeltow** [comment]
https://github.com/overtake/TelegramSwift/wiki 

Or in-app settings: **Settings > General > Keyboard Shortcut**.
