### ISSUE TITLE
Log out window: (X) closing button doesn't work

### ISSUE THREAD

**Issue by Wookbert** [overtake/TelegramSwift#411]
5.9.1 (189475) Stable

I just noticed that the (X) for closing the Log Out Overlay under Settings > Edit Profile > Log Out has absolutely no function. Clicking the shaded background works to abort the log out process works, clicking the (X) doesn't.

![Bildschirmfoto 2020-02-15 um 22 50 52](https://user-images.githubusercontent.com/3104762/74596510-8825b600-5050-11ea-8e5d-329163d9b257.png)

**Comment by zweeltow** [comment]
Fixed on last versions.
