### ISSUE TITLE
Feature Request: Helper App for notifications without running Front-end

### ISSUE THREAD

**Issue by Wookbert** [overtake/TelegramSwift#412]
_My current version: 5.9.1 (189475) Stable_

Correct me if I'm wrong, but at this point the Telegram.app has to run, in order to receive macOS notifications on incoming Telegram messages.

So if one (accidentally) quits the Telegram.app –> no more notifications.

In contrast to that macOS’s Message.app can send notifications even if the (foreground) Messages.app isn't running.

Is the same behavior (notifications despite foregrund app not running) possible with Telegram on Mac? If not now, can we expect it anytime soon?

**Comment by srfteixeira** [comment]
I was also searching for this. I guess telegram only needs to implement Apple Push Notification service in their MacOS app, as it already happens with the IOS app

**Comment by overtake** [comment]
Hi there. Mostly people are using telegram in tie with phone, i'm not sure this is good idea to spam people by notifications when the app is off. For example when i'm watching a film i just quit the app and keeping my phone beside for emergency case otherwise i can image how is irritable it would.

**Comment by srfteixeira** [comment]
Thanks, I really understand what you are saying, and in some part agree with you. But in that case, people can just turn off telegram notifications, or use the Do not Disturb feature available on MacOS Notification Center.
Apple have the plan to in the feature merge a bit of os MacOS with IOS/IpadOS, so at least in my opinion will make sense the notifications work as in IOS.

I just want to thank you for the Mac OS app, I really use everyday and love it. Thank you for  your reply and time to address this request.

Have an excellent day,
Simão Teixeira

**Comment by Wookbert** [comment]
Exactly... You can turn on „Do not disturb“ or even automatically disable it when synching wirelessly/wired to a TV or projector. So, please: Background notifications. It's a really a standard in the macOS Notifications system.

![image](https://user-images.githubusercontent.com/3104762/80697435-3cc06700-8ad9-11ea-9f97-601f39efc1a6.png)
![image](https://user-images.githubusercontent.com/3104762/80697565-6e393280-8ad9-11ea-9885-edda2d6f79b5.png)

**Comment by stlr00** [comment]
Any updates?
