### ISSUE TITLE
Double Click to reply no longer working

### ISSUE THREAD

**Issue by callumb** [overtake/TelegramSwift#413]
Version: 5.9.1 (189475) Stable

Pervious versions when you double clicked a chat you could reply, this no longer works. Reinstalling, closing and opening and even restarting has not solved the issue.

**Comment by fredhannouche** [comment]
Also broken on 5.9.3 (191685) Stable version

**Comment by sokolowadim** [comment]
Still broken in 6.0 (196005) Stable

**Comment by sokolowadim** [comment]
For those, who will find this one:

Double click is working if click on the empty space right to the message (on the same line) and not the the message (or time) itself

**Comment by callumb** [comment]
Still the same for me: 6.1.1 (197674) Stable

**Comment by zweeltow** [comment]
Works fine on 6.1.4 (200256) Stable, i guess.
