### ISSUE TITLE
Read All not wokring now.

### ISSUE THREAD

**Issue by SHELA** [overtake/TelegramSwift#416]
Before i can click on chat Icon and was READ ALL. now no such feature

**Comment by zweeltow** [comment]
On latest [beta version](https://install.appcenter.ms/users/keepcoder/apps/telegram-swift/distribution_groups/public) you can use feature "Read All".

![image](https://user-images.githubusercontent.com/50041341/86323390-6adf3600-bc45-11ea-8bb8-3d6a6fbb12fe.png)

**Comment by zweeltow** [comment]
Working on [6.2.5 (203437) Stable](https://t.me/macos_stable_updates_files/57).
