### ISSUE TITLE
Send when online not working

### ISSUE THREAD

**Issue by CollinAlpert** [overtake/TelegramSwift#423]
I am experiencing some very odd behavior when using the feature "Send when online". When I select that option, it schedules the message for the 19th of January 2038 at 3:14 UTC (which seems to be the exact date 32-bit time overflows 😉). When the user comes online, it doesn't send.

<img width="609" alt="Screen Shot 2020-03-21 at 19 27 58" src="https://user-images.githubusercontent.com/14217185/77233860-a8461900-6baa-11ea-8919-66d454d71e81.png">

**Comment by zweeltow** [comment]
Whats about last versions?

**Comment by CollinAlpert** [comment]
@zweeltow Same behavior, except that the red error icon is not being displayed anymore.

**Comment by CollinAlpert** [comment]
Where did this feature go? Was it removed?

**Comment by zweeltow** [comment]
Works fine on 6.2.2 (202143) AppStore. 

How to reproduce?

**Comment by CollinAlpert** [comment]
I just can’t find the button anymore. It seems to have disappeared. On my iPhone as well as on my Mac.

**Comment by zweeltow** [comment]
You can use “send when online” only if you share your last seen with this contact.

**Comment by CollinAlpert** [comment]
Ah, good to know. It seems to also only work if they share their last seen with me.

**Comment by zweeltow** [comment]
You're right!

**Comment by CollinAlpert** [comment]
Why are you closing this? Even though the message is scheduled, it is still scheduled for January 19th 2038.

**Comment by zweeltow** [comment]
About the [2038 year problem](https://en.wikipedia.org/wiki/Year_2038_problem) has already been reported in Telegram сhats. 

I have no reason to leave this issue.
