### ISSUE TITLE
Folders view on the left

### ISSUE THREAD

**Issue by pupaxxo** [overtake/TelegramSwift#435]
Hi,

the new telegram folders feature is AWESOME. It's really really helpful. The main issue I think we have with the Swift client, is that, if you have (3~4) folders it becomes really hard to switch between them, especially if you have "long" names. The desktop client (the not-swift one) moved them on the left, like the Discord or Slack client. Does it make sense to add it here too? Maybe configurable? The folder could have a name and an icon, then they will appear on the left. Maybe you can make them also "draggable", so you can move up and down as you want?

What do you think?

**Comment by zweeltow** [comment]
Folders view on the left already in client.
