### ISSUE TITLE
Unable to search chats

### ISSUE THREAD

**Issue by callumb** [overtake/TelegramSwift#437]
6.0 (196005) Stable

I am unable to do CMD+F to search in a chat. No longer shows the search bar at the top of the chat window. ie CMD+F does nothing.

**Comment by FranklinYu** [comment]
I’m using 6.1.1 from AppStore; <kbd>⌘</kbd> <kbd>F</kbd> works for me.

**Comment by zweeltow** [comment]
Fixed i guess.
