### ISSUE TITLE
Feature Request: Screen Sharing (VNC or RDP)

### ISSUE THREAD

**Issue by donavanbecker** [overtake/TelegramSwift#439]
It would be awesome to have the functionality of being able to do screen sharing into telegram to be able to view or control the other users screen for display or support purposes.

**Comment by vexy** [comment]
I would love to contribute to this feature, any tips on where should I start ?

**Comment by eXCoreX** [comment]
Telegram is a messenger. There're lots of other specialized apps that can do what you want.

**Comment by donavanbecker** [comment]
> Telegram is a messenger. There're lots of other specialized apps that can do what you want.

I agree. but telegram also does phone calls. It would be nice to have VNC or RDP to help support family and friends with things. Screen sharing on mobile devices to see and help them on those also.

That is why this is a Feature Request.

**Comment by zweeltow** [comment]
This suggestion for **Telegram**, not for **native Telegram for macOS**. 

You can write your suggestion in the Telegram Support in-app or from [website](https://telegram.org/support).
