### ISSUE TITLE
Annoying update badge

### ISSUE THREAD

**Issue by haskel** [overtake/TelegramSwift#441]
**The problem:** There is a big badge which calls me to update the messenger. Updates comes out daily and I need to push the badge every day to hide this big bothering message. Let me just use the messenger instead of eternally update it. The badge reminds me of interacting with Clippy in MS Word.

**Decision**: Make minor updates hidden and deactivatable.

**Comment by zweeltow** [comment]
Use stable version from [AppStore](https://apps.apple.com/us/app/telegram/id747648890?mt=12) or https://macos.telegram.org.
