### ISSUE TITLE
Slider to rewind video

### ISSUE THREAD

**Issue by ximik777** [overtake/TelegramSwift#448]
Slider for rewinding jumps to end immediately after starting video. Video plays normally, but rewind does not work.

**Operating system:**
Mac OS Catalina 10.15.4
**Version of Telegram**
6.1.2 (197946) Stable
**Used theme:**
Dark theme, night accent

**Comment by overtake** [comment]
You right. I have fixed that. Just wait 20 minutes. The version with fix on the way.

**Comment by ximik777** [comment]
Wow! Thank you very much, now everything works!
