### ISSUE TITLE
Three dots "..." instead of user name on short messages

### ISSUE THREAD

**Issue by DocteurGizmo** [overtake/TelegramSwift#449]
Hi there,

With one of the latest releases of Telegram, I get "..." instead of the user's name on short messages:
<img width="82" alt="image" src="https://user-images.githubusercontent.com/64645553/80808314-93a06c00-8bbf-11ea-9fe3-cfedc622c15a.png">

This makes understanding who is messaging a bit difficult.

Thanks!

**Comment by overtake** [comment]
I know if this. Wait please next update. It’s coming
