### ISSUE TITLE
Disable secret chats option

### ISSUE THREAD

**Issue by astorath** [overtake/TelegramSwift#45]
Hi, Telegram for MacOS supports Secret chats and auto-answers secret chat requests, even when Mac is locked. This poses two problems:

1. Security - you can not be certain, that Mac data is safe as it's on your phone,
2. Functionality - if your mac is on, you are unable to answer a secret chat from your phone (desktop app answers it itself).

I think of different options to address this:
- [ ] Add a setting to disable secret chats on desktop app completely (just ignore them)
- [ ] Stop auto-answering secret chats from the app

PS: Secret chats are way more secure on your phone: mobile app can track taking screenshots, iPhone is free of key loggers, other users can't connect to your phone. So using them on desktop is a bit weird...

**Comment by kathampy** [comment]
I have the same requirement.

**Comment by kathampy** [comment]
> @overtake Why is the issue closed? Any comments?

It’s been fixed. You can disable secret chats on macOS.

**Comment by glagola** [comment]
@kathampy Hi, where I can find the option? "Stop auto-answering secret chats from the app" I looked through all the settings section - nothing found.

**Comment by kathampy** [comment]
> 
> 
> @kathampy Hi, where I can find the option "Stop auto-answering secret chats from the app"? I looked through all the settings section - nothing found. I'm using iPad OS 14.5.1

It's only on macOS. The mobile apps always answer secret chats. You have to log out from your iPad and use only the phone.
