### ISSUE TITLE
High CPU usage while playing audio files (only if UI is visible)

### ISSUE THREAD

**Issue by voiceofmind** [overtake/TelegramSwift#453]
_Telegram Desktop 2.1.4
Mac OS 10.15.4_

**Steps:**
Send yourself an mp3 file or find it in some chat
Start playing it

**Result:**
High CPU usage

**Details and screenshots:**

Screenshot 1: normal CPU usage before playing audio
<img width="1440" alt="Снимок экрана 2020-05-10 в 19 11 31" src="https://user-images.githubusercontent.com/25658135/81504509-60ae5480-92f2-11ea-92f2-44893854d789.png">

Screenshot 2: high CPU usage while playing audio
<img width="1440" alt="Снимок экрана 2020-05-10 в 19 11 51" src="https://user-images.githubusercontent.com/25658135/81504627-09f54a80-92f3-11ea-9628-71595f4308d1.png">

Screenshot 3: normal CPU usage while **playing audio but with minimized Telegram app** (UI is not visible)
<img width="1440" alt="Снимок экрана 2020-05-10 в 19 12 11" src="https://user-images.githubusercontent.com/25658135/81504651-242f2880-92f3-11ea-8171-be606ea60877.png">

<img width="1010" alt="Об этом Mac 2020-05-10 19-13-08" src="https://user-images.githubusercontent.com/25658135/81504664-4163f700-92f3-11ea-849f-abbdfefce285.png">

**Comment by overtake** [comment]
Use macos.telegram.org
