### ISSUE TITLE
Sound pitch (speed up) on voice recording

### ISSUE THREAD

**Issue by o1dnik** [overtake/TelegramSwift#458]
If I try to record an audio message it get's very pitched-up. Does not sound normal.

Telegram version:   6.1.4 (200256) Stable

```
  OS:                   Mac OS Catalina 10.15.4
  Model Name:           MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Dual-Core Intel Core i7
  Processor Speed:	1,7 GHz
  Number of Processors:	1
```

I can reproduce it in any chat and under any conditions.
What I noticed is that the seconds on the timer are running very slow.

**Comment by zweeltow** [comment]
Try record an audio message in https://t.me/macswift for example. And please add to the description a link to this issue.

**Comment by o1dnik** [comment]
@zweeltow  in the latest beta version the record is fine, as expected!

**Comment by zweeltow** [comment]
This awesome!
