### ISSUE TITLE
Can not build from source code TelegramSwift Mac app!

### ISSUE THREAD

**Issue by KanybekMomukeyev** [overtake/TelegramSwift#47]
Hi, i am not able to build Mac app from source codes!
Have following errors:
<img width="688" alt="screen shot 2017-12-02 at 12 39 34" src="https://user-images.githubusercontent.com/866641/33512614-f615891a-d75d-11e7-8be1-ea0d58ffc26d.png">

**Comment by KanybekMomukeyev** [comment]
StepByStep followed from readme file, no success

**Comment by nikit6000** [comment]
Provided submodules references are deprecated. Clone new versions by yourself and fix few errors like   replace 'channelMembers(**account: account**, peerId: peerId)' to 'channelMembers(postbox: **account.postbox, network: account.network**, peerId: peerId)'

**Comment by KanybekMomukeyev** [comment]
@nikit6000 tried fix errors by myself, like you advised!
Where take not deprecated submodules?

What to do with this kind of errors:
<img width="975" alt="screen shot 2017-12-03 at 13 31 50" src="https://user-images.githubusercontent.com/866641/33523357-94944664-d82e-11e7-833e-e323c4187daf.png">

**Comment by tudemon** [comment]
Need support too.

**Comment by tudemon** [comment]
![image](https://user-images.githubusercontent.com/20136542/33991142-0f256398-e100-11e7-9672-682b64e3c2f3.png)

Changed many submodule version, but still get errors

**Comment by KanybekMomukeyev** [comment]
Last commit fixed everything, thanks guys!
Closing this issue!
