### ISSUE TITLE
High CPU while posting GIFs with @gif bot

### ISSUE THREAD

**Issue by antonlukin** [overtake/TelegramSwift#470]
Found a problem on the latest version. 
After sending the GIF via the `@gif` bot the CPU load increases many times and the image is not played.

<img width="304" alt="" src="https://user-images.githubusercontent.com/454185/84142430-d29aca80-aa65-11ea-8a1f-d767aa5e9f1d.png">

**Activity montior screenshot**: https://user-images.githubusercontent.com/454185/84142432-d3cbf780-aa65-11ea-997e-e5588968b6e0.png

**Chat screenshot**: https://user-images.githubusercontent.com/454185/84142434-d3cbf780-aa65-11ea-82f8-0dfb419ead7d.png

**Comment by overtake** [comment]
Hi, I have fixed that. New version will be released today

**Comment by antonlukin** [comment]
Seems ok now. Thanks
