### ISSUE TITLE
Bug: Font smoothing

### ISSUE THREAD

**Issue by proteriax** [overtake/TelegramSwift#477]
Currently Telegram for Mac does not respect the user’s system-wide setting on font smoothing:

![image](https://user-images.githubusercontent.com/8125011/85359502-68157000-b4e4-11ea-9514-629a9f0c2f24.png)

Texts look thinner and harder to read than other apps on macOS.

**Comment by proteriax** [comment]
Repo doesn’t seem to be active. Closing.

**Comment by nakp** [comment]
I think this should stay open, even now with Big Sur, that option is gone, but the code still has that setting forced

@overtake
