### ISSUE TITLE
Icon change for macOS Big Sur

### ISSUE THREAD

**Issue by ardacebi** [overtake/TelegramSwift#478]
There's an ongoing conversion to square-rounded cornered icons in macOS with the upcoming update Big Sur. All stock apps have started using these icons and many 3rd party apps are starting with the change as well.

Are there any plans for Telegram?

<img width="400" alt="Screen Shot 2020-06-25 at 12 00 05" src="https://user-images.githubusercontent.com/17576065/85689571-6c57ae00-b6db-11ea-94e5-5f36468b8f67.png">

Edit: My idea would be to use a full blue background like the iOS icon with some skeuomorphism and shadows if that's possible. The current icon really looks flat next to the Messages icon for example.

**Comment by FezVrasta** [comment]
I'd probably wait for the stable release to be released, the new icons look funny, Apple may adjust them slightly before the final release.

**Comment by ardacebi** [comment]
@FezVrasta Disagreeing, Apple has made minor changes with the icons till final release but never changed the design or the design language completely. The design of this year's macOS is surely a design like this, Skeuomorphism + Flat design + Square shaped icons.

**Comment by FezVrasta** [comment]
I'm just saying waiting a bit more won't hurt.

**Comment by Alex0007** [comment]
Dock and menubar icons look foreign to Big Sur style guide 

<img width="253" alt="image" src="https://user-images.githubusercontent.com/1143226/90248017-3cae6200-de51-11ea-9f66-b67877b67f4c.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/1143226/90248034-4932ba80-de51-11ea-9b3d-730ba20d782f.png">

**Comment by ardacebi** [comment]
@Alex0007 That's what this issue is about, see initial post for more screenshots.

**Comment by ardacebi** [comment]
@FezVrasta The GM is almost or already here. Prob won't need to wait any longer.

**Comment by thebluepotato** [comment]
Big Sur has been released this Thursday, it would make sense to include a new icon. AFAIK, it was possible to have an "old" icon and a "new" icon in the assets by following a certain naming convention but this has been removed during the beta process. There are already many nice proposals for a new Big sur Telegram icon online, but here's the reference to the Apple HIG for inspiration: https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/. In short, having some bubbly effect or 3D-feel, is the way to go.

**Comment by thebluepotato** [comment]
My current favourite is this one: 
<img width="394" alt="screenshot" src="https://user-images.githubusercontent.com/2539639/99538895-e3088700-29ad-11eb-94a6-ebdff4ab62f3.png">
[Source](https://d7m.tg/files/telegram-big-sur.html)

Combines the current icon with the roundrect and a slight bubble effect. Alternatives on [macosicons.com](https://macosicons.com) do not "fit the brief" IMO

**Comment by woj-tek** [comment]
Telegram just updated to 7.2.3 with "The sun is shining, the icon is sweet."... but - is there any way to bring back old one? Not really fond of the new one...

**Comment by thebluepotato** [comment]
I saw the update mère minutes after my suggestion above. There's no way for an app to have both a new Big Sur icon and and old one. That's why Telegram will have this icon from now on, to adapt with the news style ?even though the suggestions above would have looked *really* nice).
The only way for you to have the old icon is to find Telegram.app in the Finder, choose Get Info and drag and drop your icon of choice on the icon in that window.

**Comment by FezVrasta** [comment]
Could somebody post the new icon? I can't see the update but I'm curious

**Comment by woj-tek** [comment]
@FezVrasta  here you go:
<img width="91" alt="Captura de pantalla 2020-11-18 a las 15 18 54" src="https://user-images.githubusercontent.com/724413/99570902-5e1f6c80-29b1-11eb-9cc1-aeb81bccbf97.png">


I would appreciate link to the old one though. I tried to search repository but couldn't find it. @thebluepotato - i think that should be enough (hoping that it would stick across updates)

**Comment by mxbndr** [comment]
The squircle-with-old-icon is probably the worst design trend I can remember, right up there with Apple Address Book leaning into the literal leather imagery. Any way to permanently restore the old, round icon? I can do so temporarily but it gets replaced when telegram updates.

**Comment by d7mtg** [comment]
> My current favourite is this one: <img alt="screenshot" width="394" src="https://user-images.githubusercontent.com/2539639/99538895-e3088700-29ad-11eb-94a6-ebdff4ab62f3.png"> [Source](https://d7m.tg/files/telegram-big-sur.html)
> 
> Combines the current icon with the roundrect and a slight bubble effect. Alternatives on [macosicons.com](https://macosicons.com) do not "fit the brief" IMO

Thanks! The current implementation is pretty neat.
