### ISSUE TITLE
cpu load

### ISSUE THREAD

**Issue by restyler** [overtake/TelegramSwift#48]
Telegram often gets to 50% of cpu load and higher and my fan starts to make noise.
It does happen in regular chats even without any videos / complex gifs.
Is there any way to trace it to specific activity inside the app? Some kind of a profiler?

Telegram Version: 1.1.23
Hardware: Macbook Retina 15 (full system info attached)

<img width="209" alt="telegram2" src="https://user-images.githubusercontent.com/775507/33546701-26461fc0-d8fb-11e7-8d6c-e9421d18f45c.png">
<img width="358" alt="telegram1" src="https://user-images.githubusercontent.com/775507/33546702-266698f4-d8fb-11e7-850f-0027211d4cad.png">
<img width="130" alt="telegram_sysinfo" src="https://user-images.githubusercontent.com/775507/33546851-93301f78-d8fb-11e7-91fc-c1d754df6a4f.png">

**Comment by overtake** [comment]
This repository for native Telegram version, download it from https://macos.telegram.org and forget about CPU usage ;)
