### ISSUE TITLE
Video messages that sended from Telegram on macOS are corrupted and unplayable on other devices

### ISSUE THREAD

**Issue by upisfree** [overtake/TelegramSwift#482]
When you send video message it playable on device which from you send it but it freezed on other devices (sender and receiver). So on other devices you see preview image in poorer quality that video message are.

macOS Catalina 10.15.5, iMac (Retina 5K, 27-inch, Late 2015)
macOS Mojave 10.14.6, MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

**Comment by shafighi** [comment]
I have the same issue. It will be played only on my device. The new version of the telegram has this issue because for me and my friend it happened immediately after the upgrade.

**Comment by CssHammer** [comment]
Same

**Comment by zweeltow** [comment]
What about on [latest version](https://install.appcenter.ms/users/keepcoder/apps/telegram-swift/distribution_groups/public)?

**Comment by CssHammer** [comment]
Is there a way to update to beta from app itself? In desktop app this can be done btw

**Comment by zweeltow** [comment]
Sadly, but nope. 

Maybe [someday](https://t.me/macswift/65401).

**Comment by zweeltow** [comment]
Guys, can someone check this issue on the [latest stable version](https://t.me/macos_stable_updates_files/57)?

**Comment by upisfree** [comment]
@zweeltow I still have this issue.

macOS Catalina 10.15.6
iMac (Retina 5K, 27-inch, 2017)

6.2.3 (202354) Stable

**Comment by zweeltow** [comment]
I mean on 6.2.5 version. 

https://t.me/macos_stable_updates_files/56

**Comment by zweeltow** [comment]
Wait a few hours. I mean on 6.2.5, but now no way to update to him.

**Comment by upisfree** [comment]
I downloaded 6.2.5 from here: https://install.appcenter.ms/users/keepcoder/apps/telegram-swift/distribution_groups/public
and can't reproduce it anymore. I guess it fixed, thank you!
