### ISSUE TITLE
Add an easy way to get to Saved Messages

### ISSUE THREAD

**Issue by dancojocaru2000** [overtake/TelegramSwift#499]
I would like an easy way to get to Saved Messages. Perhaps an option in Settings like on iOS, or even a menu bar option (which could then be bound to a keyboard shortcut in System Settings too!).

**Comment by zweeltow** [comment]
Hey. You can use shortcut `⌘0` or open global search area (or use `⌘⇧F`) and go to Saved Massages. 

![image](https://user-images.githubusercontent.com/50041341/91632947-2ece1480-e9ed-11ea-97e4-47660679b052.png)

By the way, you can see all shortcuts list [here](https://github.com/overtake/TelegramSwift/wiki).

**Comment by dancojocaru2000** [comment]
The Cmd+0 shortcut is awesome!

I still think those shortcuts should be menu bar items as well to be easily discoverable, but this is great! Thank you!
