### ISSUE TITLE
Emojis are not replaced when hitting enter

### ISSUE THREAD

**Issue by TadeasKriz** [overtake/TelegramSwift#50]
Happens in Telegram 3.6.109809 Stable.

When I write: `:)` and hit Space, it correctly replaces it with an emoji. However when I write the same `:)` and hit Enter to send the message, it doesn't replace it with the emoji and just sends `:)`

Instead it should replace it with the emoji the same way hitting space does.

**Comment by overtake** [comment]
update to 3.6.1 and enjoy ;)

**Comment by TadeasKriz** [comment]
@overtake Thanks, you rock! Sorry for not trying to update, I wanted to create the issue sooner, but didn't get to it.
