### ISSUE TITLE
Large :by: emoji is displayed incorrectly

### ISSUE THREAD

**Issue by timka** [overtake/TelegramSwift#502]
Users that have Large Emoji enabled (the default) see animated white-red-white flag instead of real Belarus flag.

**Comment by timka** [comment]
I'm not familiar with TG internals, but at the first glance it looks like it's not the client app but rather the animated emoji sticker set it downloads [1]. Correct? @overtake 

[1] https://core.telegram.org/api/animated-emojis

**Comment by zweeltow** [comment]
Yes and this is not a bug. 

https://t.me/addstickers/AnimatedEmojies

![image](https://user-images.githubusercontent.com/50041341/91632830-34772a80-e9ec-11ea-807b-e5460e1f9d00.png)
