### ISSUE TITLE
macOS 11.0: Status Bar icon does not switch between light/dark icons depending on background

### ISSUE THREAD

**Issue by mreinfurt** [overtake/TelegramSwift#504]
### Steps to reproduce
1. Use latest macOS Big Sur (11.0) beta 
2. Use light theme & background image where icons appear white in status bar
3. Start Telegram
4. Watch Telegram not using the light icon

### Expected behaviour
With Big Sur, icons not only change depending on light/dark theme - but also depending on the background image.
If all other icons go white, Telegram icon should change to white as well.

Not sure how to detect how it changes in code. 
https://stackoverflow.com/questions/62685948/macos-big-sur-detect-dark-menu-bar-system-tray

### Actual behaviour
Telegram icon stays black. All other icons go white.
<img width="275" alt="telegram_icon" src="https://user-images.githubusercontent.com/493723/91980729-06655380-ed28-11ea-8a32-90759327a830.png">

### Configuration
**Operating system:** macOS Big Sur 11.0 Beta (20A5354i)

**Version of Telegram Desktop:** 7.0 (204394) AppStore

**Installation source (Linux Only)** - the official website

**Used theme**: none

**Comment by cbjeukendrup** [comment]
Most likely it has to do with `NSImage.isTemplate`. If that is set to `true`, the icon will always go white if the system thinks that would be better. (And mostly, the system is quite right ;-) )
A quick search in the source code led me to this line:
https://github.com/overtake/TelegramSwift/blob/dcb31364f5f7ffdf04d14b4ec487d38030d8585c/Telegram-Mac/SharedAccountContext.swift#L97
I wonder why it's commented out. If it were not, it would probably work.

**Comment by rickygao** [comment]
I encountered the same problem. Help needed.

**Comment by luispuerto** [comment]
Same problem here and running 7.2.2 (208387) Beta

**Comment by luispuerto** [comment]
I believe in the last update this is fixed.

**Comment by imilchev** [comment]
I am running 7.2.3 and still have this issue.

**Comment by luispuerto** [comment]
I don't 
<img width="66" alt="image" src="https://user-images.githubusercontent.com/22882880/100430407-0b237480-3097-11eb-9e2a-2b0a3e18e8c9.png">

**Comment by imilchev** [comment]
The white icon works for me too but the black one not.
![image](https://user-images.githubusercontent.com/16187050/100430645-5b023b80-3097-11eb-9f8d-17a1fec238ac.png)

**Comment by luispuerto** [comment]
ummm…. I don't have light one because I background is dark on light mode 😬

**Comment by Msouza91** [comment]
To me it is the white icon that got stuck like for @imilchev, all the other apps switch normally, it seems to really be a telegram problem.

**Comment by pbelskiy** [comment]
How to change white icon in menubar of telegram? It's quite strange to see white icon on white bar

**Comment by ajotaos** [comment]
I have this problem as well with my menu bar icon. It's weird this still hasn't got fixed.

**Comment by pbelskiy** [comment]
Probably we should write negative reviews on AppStore on Mac, to additional of here. Is it official repo of telegram for MacOS?

**Comment by theimaginationless** [comment]
We still have problem with it

**Comment by Hitsu91** [comment]
Up

**Comment by oObelix** [comment]
<img width="277" alt="Screenshot 2021-09-16 at 11 33 13" src="https://user-images.githubusercontent.com/31045630/133578931-23afa269-d6c4-4d7e-95a2-1187ec5e1ab4.png">

Same for me.
macOS Big Sur 11.5.2
Light default theme
Telegram 8.0 (220932) AppStore

**Comment by theimaginationless** [comment]
One year ago...Problem isn't fixed

**Comment by xihnik** [comment]
+

**Comment by theimaginationless** [comment]
Finally fixed!
<img width="129" alt="Снимок экрана 2021-11-04 в 15 45 06" src="https://user-images.githubusercontent.com/2709394/140315805-b1873626-d4fb-46b9-8049-1b97cb6c65fd.png">

**Comment by shikkoku** [comment]
![Screen Shot 2021-11-07 at 10 11 44 AM](https://user-images.githubusercontent.com/4697177/140629747-639093e2-25ca-4676-b1e5-14d2510568e3.png)

Still have it.
Big sur 11.6

**Comment by theimaginationless** [comment]
> ![Screen Shot 2021-11-07 at 10 16 45 AM](https://user-images.githubusercontent.com/4697177/140629865-a8a95898-4772-46f0-80ce-0dd0d3c1b95d.png)
> 
> Still have it.
> 
> Big sur 11.6

Try update to Monterey

**Comment by shikkoku** [comment]
> > ![Screen Shot 2021-11-07 at 10 16 45 AM](https://user-images.githubusercontent.com/4697177/140629865-a8a95898-4772-46f0-80ce-0dd0d3c1b95d.png)
> > Still have it.
> > Big sur 11.6
> 
> Try update to Monterey

But Telegram 8.2 (223044) Stable working just fine.

**Comment by mzakizadeh** [comment]
> Finally fixed!
> <img alt="Снимок экрана 2021-11-04 в 15 45 06" width="129" src="https://user-images.githubusercontent.com/2709394/140315805-b1873626-d4fb-46b9-8049-1b97cb6c65fd.png">


<img width="431" alt="Screen Shot 2021-11-07 at 4 19 15 PM" src="https://user-images.githubusercontent.com/10382216/140645607-3aaadadf-0a7a-45bc-aba8-bd599a6b3aba.png">
I'm on Monterey, and unfortunately, it is not fixed yet.

**Comment by theimaginationless** [comment]
> > Finally fixed!
> > <img alt="Снимок экрана 2021-11-04 в 15 45 06" width="129" src="https://user-images.githubusercontent.com/2709394/140315805-b1873626-d4fb-46b9-8049-1b97cb6c65fd.png">
> 
> <img alt="Screen Shot 2021-11-07 at 4 19 15 PM" width="431" src="https://user-images.githubusercontent.com/10382216/140645607-3aaadadf-0a7a-45bc-aba8-bd599a6b3aba.png">
> 
> I'm on Monterey, and unfortunately, it is not fixed yet.
<img width="297" alt="Снимок экрана 2021-11-07 в 16 03 48" src="https://user-images.githubusercontent.com/2709394/140646061-106621ed-647c-4ace-ab02-aadc1e6a8820.png">
My version

**Comment by shikkoku** [comment]
> > > Finally fixed!
> > > <img alt="Снимок экрана 2021-11-04 в 15 45 06" width="129" src="https://user-images.githubusercontent.com/2709394/140315805-b1873626-d4fb-46b9-8049-1b97cb6c65fd.png">
> > 
> > 
> > <img alt="Screen Shot 2021-11-07 at 4 19 15 PM" width="431" src="https://user-images.githubusercontent.com/10382216/140645607-3aaadadf-0a7a-45bc-aba8-bd599a6b3aba.png">
> > I'm on Monterey, and unfortunately, it is not fixed yet.
> 
> <img alt="Снимок экрана 2021-11-07 в 16 03 48" width="297" src="https://user-images.githubusercontent.com/2709394/140646061-106621ed-647c-4ace-ab02-aadc1e6a8820.png">
> 
> My version

This version don't have this issuse in Big sur too.
