### ISSUE TITLE
There seems no way to subscribe to a channel after an unsubscribe

### ISSUE THREAD

**Issue by scharf** [overtake/TelegramSwift#505]
I cannot find a way to subscribe to a channel after leaving it

![Demo](https://user-images.githubusercontent.com/3731059/92113249-522f0000-edef-11ea-9178-14aedab7bcce.gif)

**Comment by zweeltow** [comment]
Hey!

![image](https://user-images.githubusercontent.com/50041341/92113853-9b378200-edf8-11ea-9f0a-d050a2ec2056.png)

**Comment by scharf** [comment]
👍 wow -- I did not recognise this a a button -- banner blindness?

**Comment by scharf** [comment]
But still, why can't you subscribe where you  unsubscribe in the channel info?
