### ISSUE TITLE
Media view with external monitor shown in bad position

### ISSUE THREAD

**Issue by msudgh** [overtake/TelegramSwift#508]
With an external monitor while trying to open Image/Video media it shows the 
view box in bad position, screenshot of external monitor desktop provided.

![Screen Shot 2020-09-11 at 20 57 02](https://user-images.githubusercontent.com/11756815/92950064-599a7d00-f471-11ea-88c0-6e1f90f7cd39.png)

**Comment by smeshny** [comment]
I am experiencing the same difficulties
There is also a problem with right-clicking on a message
