### ISSUE TITLE
Bug, Bot API: Incorrect behaviour for ForceReply selective=true in a group

### ISSUE THREAD

**Issue by m1kola** [overtake/TelegramSwift#52]
It seems to me that the Telegram app for MacOS has a bug related to [`ForceReply`](https://core.telegram.org/bots/api#forcereply) with `selective=true`. It forces all MacOS users in a group to reply.

The documentation for the `selective` parameter says the following:
> `Optional`. Use this parameter if you want to force reply from specific users only. Targets: 1) users that are `@mentioned` in the text of the Message object; 2) if the bot's message is a reply (has `reply_to_message_id`), sender of the original message.

It can be reproduced in both scenarios. I've tested mentions (target 1) with [my bot](https://github.com/m1kola/shipsterbot). The second scenario with `reply_to_message_id` (target 2) can be tested with [PollBot](https://t.me/PollBot) by attempting to create a new poll.

Can reproduce on 3.6.1 (both App Store build 110227 and [downloadable versions](https://telegram.org/dl/macos)).

**Comment by m1kola** [comment]
Hm. I'm not familiar with Swift, but I didn't manage to find anything related to `selective` parameter of `ForceReply`. Probably, the app doesn't support it at all..

**Comment by SuperMasterBlasterLaser** [comment]
@m1kola I have also encountered this issue.

I have a group chat where my bot is located. My windows desktop application only force replies members that were mentioned with @ symbol in message when selective is true

However, MacOS users desktop application forces wrong members to reply
