### ISSUE TITLE
Telegram replaces -- with —

### ISSUE THREAD

**Issue by syabro** [overtake/TelegramSwift#528]
### Steps to reproduce
1. Enter `--` in text input

### Expected behaviour
Nothing happens

### Actual behaviour
It's being replaced with a long dash `—`

### Configuration
**Operating system:** MacOS

**Version of Telegram Desktop:** 7.1 (206149) Stable

**Comment by a-x-** [comment]
It’s a feature. 
Why you need `--`?

Play should use code markup

**Comment by syabro** [comment]
> Why you need --?

Because I'm writing code

> Probably you should use code markup, it prevents typography converter not it's not

No it's not @zweeltow please reopen

**Comment by syabro** [comment]
![Screen Recording 2020-10-28 at 16 13 47](https://user-images.githubusercontent.com/29029/97440654-c9d56300-1938-11eb-8ff9-77869aa86c69.gif)

**Comment by zweeltow** [comment]
> Because I'm writing code

And best way to share your code it's use the monospace. 
(By the way, you can use `⇧⌘K` shortcut for edit to monospace)

> @zweeltow please reopen

I don't look any reason reopen this issue if it's a feature.

**Comment by a-x-** [comment]
> don't look any reason reopen this issue if it's a feature.

Telegram should prevent converting if ` symbol present at line

**Comment by syabro** [comment]
@a-x- my bad. Turned out replacing was enabled in my Mac OS. I was pretty sure I turned it off :(
