### ISSUE TITLE
Spotify preview in links don't work 

### ISSUE THREAD

**Issue by rahulahoop** [overtake/TelegramSwift#531]
When sending song links in telegram, one cannot see the song information preview 

<img width="809" alt="Screen Shot 2020-10-23 at 10 03 20 AM" src="https://user-images.githubusercontent.com/7705259/96972602-fcd1be00-1516-11eb-8ef0-5efa6604e09f.png">

same problem also in the iOS app

**Comment by zweeltow** [comment]
This is not a bug of telegram for macOS.

**Comment by rahulahoop** [comment]
where to post this then ? @zweeltow

**Comment by zweeltow** [comment]
> where to post this then ? @zweeltow

You can write to the Telegram Support in-app (in settings) or via website: https://telegram.org/support.
