### ISSUE TITLE
Repeated nick in groups since Telegam 7.1

### ISSUE THREAD

**Issue by Lju88** [overtake/TelegramSwift#533]
Since Telegram 7.1 the nickname is repeated for every consecutive message inside a group conversation when Bubble Mode is disabled. Reverting to 7.0 fixes the problem.

7.0 Behaviour (correct):
![Screenshot 2020-10-27 at 11 11 26](https://user-images.githubusercontent.com/11982322/97288342-03797180-1846-11eb-95d5-41d0be9ff305.jpg)

7.1 Behaviour (wrong):
![Screenshot 2020-10-27 at 11 12 09](https://user-images.githubusercontent.com/11982322/97288354-08d6bc00-1846-11eb-91bc-cf02ecfe0627.jpg)

**Comment by overtake** [comment]
Yes.I have fixed it. Will be ok in next release. Sorry for that

**Comment by Lju88** [comment]
Thank you!
