### ISSUE TITLE
Slotmachine: Beacon flashes while drums are still spinning

### ISSUE THREAD

**Issue by Wookbert** [overtake/TelegramSwift#540]
Not really a bug, more a logical/graphical glitch: I noticed that every time the :slotmachine: Animation is about to win, the top red beacon flashes while the drums are still spinning and the actual result isn't there yet. It shouldn't go off however until the last drum has stopped.

![image](https://user-images.githubusercontent.com/3104762/98553488-f45fde00-229f-11eb-9378-55bcd8d82281.png)

P.S.: It would be slick if the tray would be filled with golden coins on a win (+ sound?).

**Comment by zweeltow** [comment]
Hey. It's not a Telegram macOS bug. You can suggestion it to the Telegram Support in-app (in settings) or via website: https://telegram.org/support.
