### ISSUE TITLE
Incorrectly cached inline query results

### ISSUE THREAD

**Issue by revolter** [overtake/TelegramSwift#55]
#### Reproducing steps:

1. Reopen `Telegram`
2. Open a chat
3. Type `@UrbanDictionaryBot good`
4. Delete the entire input field
5. Type `@UrbanDictionaryBot bad`

#### Actual:

The results of the `good` query show up.

#### Expected:

New results should be fetched for the `bad` query.

#### Notes:

Reopening `Telegram` clears the incorrect "cache" (most probably an in-memory, not needed, cache) so typing `@UrbanDictionaryBot bad` again, immediately after opening it, shows the correct results.

#### Version:

`3.6.1.110227`

**Comment by izanmubarak** [comment]
Also having this issue. Extremely frustrating, although I've found you can just click "Back" for the cache to clear.

**Comment by avatar29A** [comment]
3.7.5 also this error there is. It's very unpleasant error, bots that provides suggesting functions are broken. :(

**Comment by overtake** [comment]
fixed thanks.
