### ISSUE TITLE
More than 3 accounts same time

### ISSUE THREAD

**Issue by totaleo** [overtake/TelegramSwift#557]
Hi. It's possible to have more than 3 active telegram accounts same time if I change limit in source code?

I found mentions of maximum accounts in lines:
https://github.com/overtake/TelegramSwift/blob/3fdc53a43a7c832ed1dac7e643569eb92730f5e3/Telegram-Mac/LogoutViewController.swift#L59
https://github.com/overtake/TelegramSwift/blob/0c572405f9a7d6fc143d8828c8564dd8d9508410/Telegram-Mac/EditAccountInfoController.swift#L214
https://github.com/overtake/TelegramSwift/blob/0c572405f9a7d6fc143d8828c8564dd8d9508410/Telegram-Mac/EditAccountInfoController.swift#L222

**Comment by zweeltow** [comment]
Actually you can have more then 3 account right now. 

Just go to the developer menu (5 tap on settings icon) > Add Account.

**Comment by totalleo** [comment]
Wow. That works. Thank you for this hidden feature.

**Comment by zweeltow** [comment]
You are welcome!

**Comment by thecaralice** [comment]
> Just go to the developer menu (5 tap on settings icon) > Add Account.

Does that still work? I'm unable to open the developer menu. I also have my profile picture instead of the settings icon - maybe that's the cause?

**Comment by harryqt** [comment]
How add more than 3 account on current latest version?

**Comment by vladkens** [comment]
@harryqt buy Telegram Premium or same as before should work (`Just go to the developer menu (5 tap on settings icon) > Add Account.`)
