### ISSUE TITLE
Top bar icon not adapting on dynamic background

### ISSUE THREAD

**Issue by antonstsk** [overtake/TelegramSwift#560]
When using the adaptive wallpaper the top bar changes it's colour. Telegram icon is not adapting.
<img width="289" alt="Screenshot 2020-12-09 at 10 34 51" src="https://user-images.githubusercontent.com/33395021/101611816-44020880-3a0a-11eb-918f-b27ba376a742.png">

MacOS version: Big Sur 11.0.1
Telegram version: 7.2.4

**Comment by antonlukin** [comment]
Possibly duplicate #542

**Comment by antonstsk** [comment]
@antonlukin seems like it, closing the issue
