### ISSUE TITLE
MacOS shared item  does not work as expected

### ISSUE THREAD

**Issue by imyelmo** [overtake/TelegramSwift#563]
I have the option of sharing items via the MacOS share service (i.e., screen capture). I can choose telegram and the destination contact and click to share the capture but the screen capture is never sent to the contact as expected. This worked previously. I do not know if it is because some recent change. Let me know if I can help in anyway.

**Comment by zweeltow** [comment]
Seems that has been fixed. Can you check in latest beta version? https://telegram.org/dl/macos/beta

**Comment by imyelmo** [comment]
I can confirm that the issue is fixed in the beta. Great work! It is something really helpful!
