### ISSUE TITLE
Sharing links( like t.me/share/url?url= ) are ignoring uppercase

### ISSUE THREAD

**Issue by vargroozzz** [overtake/TelegramSwift#564]
When you share anything via sharing link, all uppercase letters will be replaced by lowercase ones:

<img width="634" alt="Снимок экрана 2020-12-17 в 15 18 32" src="https://user-images.githubusercontent.com/40725019/102493266-9c28b280-407b-11eb-8403-da5c3eeb869a.png">
<img width="628" alt="Снимок экрана 2020-12-17 в 15 19 10" src="https://user-images.githubusercontent.com/40725019/102493274-9d59df80-407b-11eb-82fa-0b29c1b96165.png">
<img width="628" alt="Снимок экрана 2020-12-17 в 15 19 30" src="https://user-images.githubusercontent.com/40725019/102493277-9df27600-407b-11eb-8e84-065743c92e91.png">

This can affect work of some bots.
P.S This problem is only in macOS client, in iOS client sharing works correct

**Comment by francisyzy** [comment]
I think its this .lowercased causing the issue. Did not pull and test it on Xcode tho.

https://github.com/overtake/TelegramSwift/blob/67e4cf8de2f060ec8152ce68562c9489a6073534/Telegram-Mac/InAppLinks.swift#L1269-L1271

**Comment by overtake** [comment]
you right. fixed
