### ISSUE TITLE
[Bug] Share menu not showing on Big Sur

### ISSUE THREAD

**Issue by ji3g4m6zo6** [overtake/TelegramSwift#568]
## Steps to reproduce ##

![image](https://i.imgur.com/dXgjebz.gif)

## Expected behaviour ##

Pop up an UI for sharing.

## Actual behaviour ##

Nothing happened.

### Operating system ###
macOS Big Sur 11.1（20C69）

### Version of Telegram Desktop ###
7.3 (211493) Beta

### Installation source ### 
App Center

### Used theme ###
Day Classic

**Comment by zweeltow** [comment]
Seems like that's fixed on latest version.

**Comment by ji3g4m6zo6** [comment]
I'm using the latest version which is 7.4 (212543). It seems that hasn't been fixed.

**Comment by zweeltow** [comment]
Works fine for me on 7.4 (212543) Beta, strange. 🤔 

Did you try to reinstall the app? Or maybe you did turn off some security setting?
