### ISSUE TITLE
Зависание телеграмма

### ISSUE THREAD

**Issue by mounlion** [overtake/TelegramSwift#57]
1. Открываем фотку
2. Нажимаем Сохранить
3. В открывшимся диалоговом окне пытаемся создать новую папку
4. Телега виснет на мертво.

**Comment by overtake** [comment]
Не воспроизводится. Попробуй перезапустить систему.

**Comment by mounlion** [comment]
Может дело в оси. У меня 10.13.2

**Comment by overtake** [comment]
У меня тоже. Все таки попробуй перезапустить.

**Comment by mounlion** [comment]
Перезапустил. Не помогло.
среда, 13 декабря 2017 г., 16:50 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by overtake** [comment]
На всех фотках, или только на одной?

**Comment by mounlion** [comment]
На всех. Вот видео
[2017-12-13 17.03.09.mp4.zip](https://github.com/overtake/TelegramSwift/files/1555723/2017-12-13.17.03.09.mp4.zip)

**Comment by overtake** [comment]
А, вот так воспроизводится. Можно нажать esc и отпустит его. А баг системный, к сожалению. Эпл последнее время удивляет с обновлениями и багами внезапных в них.

**Comment by mounlion** [comment]
Дело в том что esc не срабатывает. Приходится через диспетчер убывать :(

**Comment by overtake** [comment]
я раза 2 нажал esc и у меня сработало ;)

**Comment by mounlion** [comment]
Да) Сработало!

**Comment by mounlion** [comment]
И еще вопрос. Раньше чат с самим собой был в контакта. Потом в его переместили в настройки. Но в мак версии этого нет(

**Comment by overtake** [comment]
Нажми на поиск, там будет Saved Messages первым пунктом.

**Comment by mounlion** [comment]
Спасибо за ответ)
Лови новый баг

1.  Открой изображение в полный экран
2. Переключись на другой экран
3. Затем опять переключись на экран с телегой
4. Происходи моргание изображение скрываться и появляется
