### ISSUE TITLE
Crash when trying to send location

### ISSUE THREAD

**Issue by jerielng** [overtake/TelegramSwift#576]
### Reproduction Steps
1. Open a private chat with another user
2. Hover over the attachments icon to open the menu
3. Click on `Location`
4. App will crash if location services is not enabled in system privacy settings

App version: 7.3 (211379) AppStore
Device info: macOS 11.1, MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)

**Comment by zweeltow** [comment]
Hey! Can you check this bug on latest stable version (7.4 (212543))?

**Comment by jerielng** [comment]
> Hey! Can you check this bug on latest stable version ([7.4 (212543)](https://t.me/macos_stable_updates_files/82))?

@zweeltow Hey, I just ran 7.4 from that link and it appears that issue is no longer happening!

**Comment by rschiang** [comment]
I could stably reproduce this on the current version (7.6 (214318) AppStore). Wonder if it’s a regression or some newly introduced CoreLocation behavior?

Device info: macOS 11.2.3, MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)  
Relevant stack trace:

<details>

```
Thread 26 Crashed:: Dispatch queue: com.apple.CoreLocation.0x7f828eaff410
0   libsystem_kernel.dylib        	0x00007fff2033f462 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff2036d610 pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff202c0720 abort + 120
3   com.apple.corelocation        	0x00007fff2828f382 0x7fff28286000 + 37762
4   com.apple.locationsupport     	0x00007fff2cbac1d6 0x7fff2cb9b000 + 70102
5   com.apple.locationsupport     	0x00007fff2cbac135 0x7fff2cb9b000 + 69941
6   com.apple.locationsupport     	0x00007fff2cb9ec02 CLConnection::handleMessage(std::__1::shared_ptr<CLConnectionMessage>) + 360
7   com.apple.locationsupport     	0x00007fff2cba794b 0x7fff2cb9b000 + 51531
8   com.apple.locationsupport     	0x00007fff2cba9009 0x7fff2cb9b000 + 57353
9   libxpc.dylib                  	0x00007fff200b0c28 _xpc_connection_call_event_handler + 56
10  libxpc.dylib                  	0x00007fff200afa9c _xpc_connection_mach_event + 935
11  libdispatch.dylib             	0x00007fff201c2867 _dispatch_client_callout4 + 9
12  libdispatch.dylib             	0x00007fff201d9a47 _dispatch_mach_msg_invoke + 441
13  libdispatch.dylib             	0x00007fff201c84a7 _dispatch_lane_serial_drain + 263
14  libdispatch.dylib             	0x00007fff201da5b8 _dispatch_mach_invoke + 498
15  libdispatch.dylib             	0x00007fff201c84a7 _dispatch_lane_serial_drain + 263
16  libdispatch.dylib             	0x00007fff201c90cb _dispatch_lane_invoke + 375
17  libdispatch.dylib             	0x00007fff201d2c5d _dispatch_workloop_worker_thread + 819
18  libsystem_pthread.dylib       	0x00007fff2036a499 _pthread_wqthread + 314
19  libsystem_pthread.dylib       	0x00007fff20369467 start_wqthread + 15
```

</details>

**Comment by anvarkhamidov** [comment]
> I could stably reproduce this on the current version (7.6 (214318) AppStore). Wonder if it’s a regression or some newly introduced CoreLocation behavior?
> 
> Device info: macOS 11.2.3, MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
> Relevant stack trace:
> 
> ```
> Thread 26 Crashed:: Dispatch queue: com.apple.CoreLocation.0x7f828eaff410
> ```

I think, you should open a new issue, since this is closed.
