### ISSUE TITLE
Do not convert "8)" to emoji

### ISSUE THREAD

**Issue by leoblum** [overtake/TelegramSwift#585]
Hi. I often use numbered lists when I'm chatting on Telegram. Everything is cool except when I get to the eighth menu item I write "8)" and it automatically turns into "😍" emoji. It's weird, especially in business correspondence.

Please can you make it like when I write a numbered list, the eighth item doesn't turn into an emoji. And when my partner receive the message he also will see "8)" instead of an emoji.

Example:
6) blah blah blah.
7) blah blah blah.
8) blah-blah-blah // Because there were "6)" and "7)" before, "8)" did not turn into an emoji

But if I just write a text like, "you're awesome 8)" its translates to "you're awesome 😍".

Or, if that will be easier to you, maybe you can change the combination for "😍" from "8)" to "8-)" or something.

**Comment by zweeltow** [comment]
Hey. 
You can disable **Replace Emoji Automatically** in _Settings > General_. 

![image](https://user-images.githubusercontent.com/50041341/106180829-e4c0a900-61ad-11eb-9d50-7640a68dc775.png)

By the way, for fast use emoji you should use "_:_".

Example:
![image](https://user-images.githubusercontent.com/50041341/106181114-3b2de780-61ae-11eb-961e-9459dd26e5cc.png)
