### ISSUE TITLE
Pictures in full screen not fitting on dual monitor

### ISSUE THREAD

**Issue by brasofilo** [overtake/TelegramSwift#587]
I'm running Telegram Desktop v2.5.8 on MacOS 10.14.6, MacBookPro 13" Mid 2012, Graphics Intel HD 4000 1536 MB.

When I click an image on the second monitor it displays as if was zoomed like 150%:

<kbd>![second-monitor](https://user-images.githubusercontent.com/1542052/107159951-08d07700-6972-11eb-817b-5ee05e33a9b4.png)</kbd>

This is the laptop screen showing the correct proportion/scale:

<kbd>![laptop-monitor](https://user-images.githubusercontent.com/1542052/107159984-256caf00-6972-11eb-8dae-a405de7183dd.png)</kbd>

I'm not positive but I think it was working ok and then it wasn't but I can't pinpoint the bug to a specific update.

**Comment by zweeltow** [comment]
Hey! Unfortunately you report this issue in wrong repository. You should report issue to [the repository of Telegram Desktop](https://github.com/telegramdesktop/tdesktop/issues).
