### ISSUE TITLE
Doesn't send voice messages until app restart

### ISSUE THREAD

**Issue by eyehol3** [overtake/TelegramSwift#593]
it sends it just ok to saved messages. but it doesn't to any other chat until i restart telegram.

**Comment by upisfree** [comment]
@overtake the same for video messages and sometimes for photos. An app became nearly unusable right after latest update.

Telegram 7.5 (213379) Stable
macOS 11.2.1 (20D74)
iMac (Retina 5K, 27-inch, 2017)

**Comment by upisfree** [comment]
Created issue at Telegram bugs platform: https://bugs.telegram.org/c/2700
