### ISSUE TITLE
DarkMode gone and no appearance section in 3.7

### ISSUE THREAD

**Issue by Zapnick** [overtake/TelegramSwift#62]
Hi guys, 3.7. removed the dark mode for me and there is no appearance section under settings. Tested under 10.13.2.

**Comment by overtake** [comment]
Please post screenshot of your settings

**Comment by Zapnick** [comment]
![telegram 2017-12-24 21-43-15](https://user-images.githubusercontent.com/26958284/34329120-84bf5cee-e8f3-11e7-90ff-49b803a64509.png)

**Comment by overtake** [comment]
Uncollapse dialogs and go to full settings menu

**Comment by Zapnick** [comment]
this is all i have, nothing what i could uncollapse no full settings

**Comment by overtake** [comment]
I see you are using collapsed dialogs mode. Hold you Mouse on corner between left part and Right part of the app and slide right . Then you will see tabs with contacts/calls/chats and settings.

**Comment by Zapnick** [comment]
ok, got it. thank you. had no idea that the collapsed contact panel has influence on the settings dialog. 

thank you very much
