### ISSUE TITLE
There is no "show NSFW content" switch in the settings

### ISSUE THREAD

**Issue by xm4dn355x** [overtake/TelegramSwift#631]
MacOS Telegram Desktop users cannot view NSFW content even with filters disabled in macOS system settings. In the macOS Telegram Desktop settings, there is no switch that allows you to disable NSFW content filtering. This complicates the work, since you have to constantly use non-macOS devices.

**Comment by zweeltow** [comment]
Hey! Unfortunately you report this issue in wrong repository. You should report issue to [the repository of Telegram Desktop](https://github.com/telegramdesktop/tdesktop/issues).

**Comment by xm4dn355x** [comment]
> Hey! Unfortunately you report this issue in wrong repository. You should report issue to [the repository of Telegram Desktop](https://github.com/telegramdesktop/tdesktop/issues).

Thanks, bro))

Interesting, but link on telegram.org was only to this repo))

**Comment by xm4dn355x** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16346

They said that is Telegram Swift, not Telegram Desktop.
