### ISSUE TITLE
SHA256 Changed Confirmation for v3.7.1-111991

### ISSUE THREAD

**Issue by ElfSundae** [overtake/TelegramSwift#66]
It seems the `sha256` hash of the current version `3.7.1-111991` has been changed, and this causes installation via Homebrew Cask will fail, see https://github.com/caskroom/homebrew-cask/issues/42427

I have submitted a PR to fix this https://github.com/caskroom/homebrew-cask/pull/42426 but it needs a confirmation from the developer, FYI https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

@overtake Could you please respond something here? Thanks 😄

**Comment by ElfSundae** [comment]
That PR just been merged.

**Comment by magicgoose** [comment]
So actually all the "confirmation" was just a virustotal scan? Seriously?
