### ISSUE TITLE
Unable to send an image, a recorded voice

### ISSUE THREAD

**Issue by fisenkodv** [overtake/TelegramSwift#67]
Unable to send an image(png, jpeg), Telegram only shows "clock" loader on an image.
Telegram: 3.7.1.111991
macOS: 10.13.2

**Comment by florianweich** [comment]
Same problem here. Also true for recorded voice messages.
Telegram: 3.7.5.115423
macOS: 10.13.2

**Comment by fisenkodv** [comment]
Any updates?

**Comment by Lweek** [comment]
Have same problem but only with particular user. I can send him image from all clients except this one. He can send me images without limitation.

**Comment by nasredin** [comment]
same for me... :(
