### ISSUE TITLE
Feature Request: Allow image preview using macOS Preview app for its auto OCR feature

### ISSUE THREAD

**Issue by satwanjyu** [overtake/TelegramSwift#677]

**Comment by AJAYK-01** [comment]
Seems like the Preview app need not be invoked, the auto ocr can be added to Telegram's Preview itself as Apple has exposed this api 
https://developer.apple.com/documentation/vision/locating_and_displaying_recognized_text

**Comment by AJAYK-01** [comment]
This feature seems to be added to Telegram MacOs now @satwanjyu 
I think it should be closed now.
