### ISSUE TITLE
No badge and sound notification options in System Preferences

### ISSUE THREAD

**Issue by neposedy-design** [overtake/TelegramSwift#691]
Telegram 8.1.3 (222037) AppStore
macOS 12.0.1 (21A559) (MacBook Pro)

Badge and sound options are not available in System Preferences / Notifications / Telegram prefpane. Already tried completely removing app and all of its files from ~\Library\, reinstalled to no avail. 
This happened after fresh macOS Monterey install. 

![Screen Shot 2021-10-28 at 18 59 08](https://user-images.githubusercontent.com/70030433/139296650-bd77b0a0-1f08-4449-aae8-b45af9404133.jpg)

![Screen Shot 2021-10-28 at 19 11 42](https://user-images.githubusercontent.com/70030433/139296675-bf30b874-30fa-44da-b32e-28a21e17e4ef.jpg)

**Comment by akrabat** [comment]
I have the same problem on a fresh install of "8.2 (222902) Stable" on Monterey on my M1 MacBook Pro.

**Comment by gekich** [comment]
same here on
Telegram macOS, 8.2 (222970) STABLE, MacBook Pro 14" M1 Pro, macOS, 12.0.1

**Comment by malyshevko** [comment]
same here
<img width="1446" alt="Снимок экрана 2021-11-09 в 11 15 26" src="https://user-images.githubusercontent.com/15076676/140887204-1d2167c5-d30e-43dd-bee7-07d47e24a56f.png">

**Comment by karlhorky** [comment]
I got caught out by this, installing this unofficial TelegramSwift client by accident with Homebrew.

However, the official Telegram Desktop client has badges on macOS Monterey!

<img width="160" alt="Screen Shot 2021-11-11 at 18 51 19" src="https://user-images.githubusercontent.com/1935696/141345521-13d8208c-6928-49fb-8276-f7bf7cc8f814.png">

Here on Homebrew: https://formulae.brew.sh/cask/telegram-desktop

**Comment by Aokromes** [comment]
> I got caught out by this, installing this unofficial TelegramSwift client by accident with Homebrew. Even reported it in the Telegram Desktop repo: [telegramdesktop/tdesktop#17230](https://github.com/telegramdesktop/tdesktop/issues/17230)
> 
> However, the official Telegram Desktop client has badges and sound on macOS Monterey!
> 
> <img alt="Screen Shot 2021-11-11 at 18 51 19" width="160" src="https://user-images.githubusercontent.com/1935696/141345521-13d8208c-6928-49fb-8276-f7bf7cc8f814.png">
> 
> Here on Homebrew: [formulae.brew.sh/cask/telegram-desktop](https://formulae.brew.sh/cask/telegram-desktop)

both clients are official.

**Comment by karlhorky** [comment]
Ok, thanks for the tip, sorry for the incorrect assumption! I've edited my post above.

**Comment by Blinks44** [comment]
Same, so we wait for update or badges won't never coming back in telegram for macOS?

**Comment by kryri** [comment]
Any word on this? I have the same problem and I really want those badges back!

**Comment by jlubeck** [comment]
Same issue here and it's super annoying :( 

M1 computer on Monterey as well

**Comment by countfak** [comment]
just got an app update, bug should be fixed. I had to go to system preferences > notifications settings and remove the entry for telegram (just select telegram on the left and press delete). telegram will then ask you permission for notifications when you receive a message, and it should start working. also uninstalling and reainstalling the app should work the same.

**Comment by akrabat** [comment]
This hasn't worked for me with version `8.3 (223729) Stable`. I deleted, downloaded from the website and re-installed.

**Comment by neposedy-design** [comment]
Surprisingly, just deleting Telegram's entry in Sys Prefs > Notifications worded for me in 8.2 (AppSore), badges and sounds are working. 
Close an app, go to sys prefs - notifications pref pane, select Telegram entry, press Delete on your keaboard, launch Telegram app.

**Comment by kryri** [comment]
Removing the Entry in Notifications worked for me, thank you!

**Comment by timkite** [comment]
Removing the Entry in Notifications did NOT work for me, and now there are no notifications whatsoever, with no obvious way to re-enable them (Mac App Store version, currently 8.3 (223733) AppStore). I've also tried completely removing the app and all support files, then re-installing from the Mac App Store. This gives me the prompt to re-enable notifications, but the options for badges and sounds are still missing.

**Comment by neposedy-design** [comment]
> Removing the Entry in Notifications did NOT work for me, and now there are no notifications whatsoever, with no obvious way to re-enable them (Mac App Store version, currently 8.3 (223733) AppStore). I've also tried completely removing the app and all support files, then re-installing from the Mac App Store. This gives me the prompt to re-enable notifications, but the options for badges and sounds are still missing.
@timkite

Weird. For me, the Telegram's entry in Focus/Notifications pref pane reappears each time I reinstall an app and open Notifications preferences (in app), or send myself a message from another Telegram account. Tested in 8.2 and 8.3 (MAS).

**Comment by timkite** [comment]
> Weird. For me, the Telegram's entry in Focus/Notifications pref pane reappears each time I reinstall an app and open Notifications preferences (in app), or send myself a message from another Telegram account. Tested in 8.2 and 8.3 (MAS).

Further fiddling has revealed that if, after re-installation, I click the "Reset Notifications" option in Telegram, then quit and restart the app I get the red "!" in Telegram's Notifications preferences to re-enable macOS notifications (though not the standard system notification asking to enable notifications that other apps have). Even doing all that, though, "badges" and "sounds" are not options that can be enabled, but at least banners and such are there again.

<img width="780" alt="Screen Shot 2021-12-14 at 17 19 08" src="https://user-images.githubusercontent.com/6933976/146088484-d25f6a90-87dc-4e4a-b4a6-fed46256380b.png">

I also discovered that "Telegram Lite" works as a substitute since it does support badges, though is very obviously not a native application.

**Comment by allie** [comment]
No luck for me either, removing Telegram from Notifications & Focus didn't solve my problem. Re-enabling it again once I get a message only shows the lock screen and notification centre options, but no badge or sound options. I use two user accounts on my machine (one for personal use and one for work), and weirdly, badges are working properly one one of my accounts but not the other. macOS Monterey 12.1, 2021 14" MacBook Pro, Mac App Store version.

**Comment by margushev** [comment]
!!! IMPORTANT !!! Do not use the Telegram Settings Menu to Allow notification as it will break the notifications - This is the thing that was bugging me the most. !!! IMPORTANT !!!
If you do you will have to remove Telegram from the MacOSX Notifications in System Preferences

I've spend several days in order to figure this out.
Follow this guide step by step and it will work for you as well.

1. Install Telegram Swift [(MacOSX client)( either from AppStore or from official download site )] - skip if you already have it installed.
2. Quit Telegram
3. Go to the System Preferences - Notifications and Focus -
  Find Telegram in the list and press Command + Backspace to delete the entry
4. Launch Telegram and wait for some notification ( Or text yourself from different account ) - You will receive notification in the top right corner from Telegram to configure the notifications.

Both sound notifications and badge icon should be working. Enjoy :)

**Comment by timkite** [comment]
> !!! IMPORTANT !!! Do not use the Telegram Settings Menu to Allow notification as it will break the notifications - This is the thing that was bugging me the most. !!! IMPORTANT !!! If you do you will have to remove Telegram from the MacOSX Notifications in System Preferences
> 
> I've spend several days in order to figure this out. Follow this guide step by step and it will work for you as well.
> 
> 1. Install Telegram Swift [(MacOSX client)( either from AppStore or from official download site )] - skip if you already have it installed.
> 2. Quit Telegram
> 3. Go to the System Preferences - Notifications and Focus -
>    Find Telegram in the list and press Command + Backspace to delete the entry
> 4. Launch Telegram and wait for some notification ( Or text yourself from different account ) - You will receive notification in the top right corner from Telegram to configure the notifications.
> 
> Both sound notifications and badge icon should be working. Enjoy :)

Sadly still did not work for me. Followed those instructions and had a friend message me. Did not get the notification tip asking for notifications to be enabled, but Telegram did then re-appear in Notifications and Focus preferences...still without badges or sounds as options. Using the App Store version of Telegram Swift on an M1 Max MacBook Pro 14".

**Comment by margushev** [comment]
> > !!! IMPORTANT !!! Do not use the Telegram Settings Menu to Allow notification as it will break the notifications - This is the thing that was bugging me the most. !!! IMPORTANT !!! If you do you will have to remove Telegram from the MacOSX Notifications in System Preferences
> > I've spend several days in order to figure this out. Follow this guide step by step and it will work for you as well.
> > 
> > 1. Install Telegram Swift [(MacOSX client)( either from AppStore or from official download site )] - skip if you already have it installed.
> > 2. Quit Telegram
> > 3. Go to the System Preferences - Notifications and Focus -
> >    Find Telegram in the list and press Command + Backspace to delete the entry
> > 4. Launch Telegram and wait for some notification ( Or text yourself from different account ) - You will receive notification in the top right corner from Telegram to configure the notifications.
> > 
> > Both sound notifications and badge icon should be working. Enjoy :)
> 
> Sadly still did not work for me. Followed those instructions and had a friend message me. Did not get the notification tip asking for notifications to be enabled, but Telegram did then re-appear in Notifications and Focus preferences...still without badges or sounds as options. Using the App Store version of Telegram Swift on an M1 Max MacBook Pro 14".

It is important to not launch Telegram second time - meaning don't quit after you remove the entry in notifications and focus and launch it. 
!!! And do not use the Telegram Settings to Allow Notifications. 
I've tested that several times myself. - Works every single time.

**Comment by timkite** [comment]
> It is important to not launch Telegram second time - meaning don't quit after you remove the entry in notifications and focus and launch it. !!! And do not use the Telegram Settings to Allow Notifications. I've tested that several times myself. - Works every single time. Make sure that Telegram is minimised, closed (not Quit) or hidden during the receiving of the message! Otherwise it might not popup in the right corner of your screen.
> 
> P.S. - May be try using AppCleaner to fully remove Telegram and install it again and try this steps one more time.

Yeah, I did exactly that, twice now (and with an AppCleaner attempt the last time). That said, I've never encountered an app is like this, requiring this much fiddling to make notifications work. I'll probably honestly just switch over to Telegram Lite for when I need Telegram on a Mac at this point.

**Comment by ewqqx** [comment]
Finally! After so many days I've fixed this by @margushev's tips. Pay attention - don't quit after you remove telegram entry in notifications, it will not work if you do. You need to remove the entry from notifications and send to your self a message without quiting telegram, just close it. Then there will be a pop up message asking to turn on notifications for app.

**Comment by neposedy-design** [comment]
https://github.com/overtake/TelegramSwift/issues/691#issuecomment-997976633

**Comment by overtake** [comment]
Hi guys. Sorry for that, probably i found solution for this. Hope fix will be included to 8.4.1. I sent it to review right now

**Comment by Finegorko** [comment]
still no sound sir ;(

**Comment by outring** [comment]
@overtake I was using an AppStore version but yesterday decided to switch to a regular one, just uninstalled the old one the usual way and installed the new one (8.4.1 (225774) Stable) and can't get notifications to work (get no badge in Dock, no alerts). Telegram doesn't appear in Notification Settings no matter what I do. What I tried so far:
1. Remove Telegram and all related data in ~/Library and /Library (`find . -iname *telegram*`)
2. Reset Notification Center settings (`rm ~/Library/Preferences/com.apple.ncprefs.plist`)
3. Installing Telegram from dmg again
4. Reboot before, after and in the middle of the process 🤯 lol

When I start Telegram for the first time after this I see no OS prompt to allow/disallow notifications for the app like it happens with other apps
Should I open a new issue for that?

macOS 11.6

**Comment by Finegorko** [comment]
> @overtake I was using an AppStore version but yesterday decided to switch to a regular one, just uninstalled the old one the usual way and installed the new one (8.4.1 (225774) Stable) and can't get notifications to work (get no badge in Dock, no alerts). Telegram doesn't appear in Notification Settings no matter what I do. What I tried so far:
> 
>     1. Remove Telegram and all related data in ~/Library and /Library (`find . -iname *telegram*`)
> 
>     2. Reset Notification Center settings (`rm ~/Library/Preferences/com.apple.ncprefs.plist`)
> 
>     3. Installing Telegram from dmg again
> 
>     4. Reboot before, after and in the middle of the process 🤯 lol
> 
> 
> When I start Telegram for the first time after this I see no OS prompt to allow/disallow notifications for the app like it happens with other apps Should I open a new issue for that?
> 
> macOS 11.6

try this https://github.com/overtake/TelegramSwift/issues/691#issuecomment-997976633

**Comment by timkite** [comment]
> @overtake I was using an AppStore version but yesterday decided to switch to a regular one, just uninstalled the old one the usual way and installed the new one (8.4.1 (225774) Stable) and can't get notifications to work (get no badge in Dock, no alerts). Telegram doesn't appear in Notification Settings no matter what I do. What I tried so far:
> 
> 1. Remove Telegram and all related data in ~/Library and /Library (`find . -iname *telegram*`)
> 2. Reset Notification Center settings (`rm ~/Library/Preferences/com.apple.ncprefs.plist`)
> 3. Installing Telegram from dmg again
> 4. Reboot before, after and in the middle of the process 🤯 lol
> 
> When I start Telegram for the first time after this I see no OS prompt to allow/disallow notifications for the app like it happens with other apps Should I open a new issue for that?
> 
> macOS 11.6

For what it's worth, I was having this exact problem too, and previous attempts to fix it (like following comment #691) didn't work at all for me. Then, I updated to App Store version 8.4.1 (225801) (note the _slightly_ newer build version vs. yours) and the problem fixed itself, mostly. Prior to the update, Telegram didn't appear at all in my Notification preferences because I had followed the instructions mentioned and even new notifications coming in didn't get it to re-appear. After the update (and launching Telegram), Telegram appeared in my notification preferences, but was disabled by default. It seems Telegram Swift is still not asking macOS for the standard "do you want to enable notifications" notification, but I found that simply manually going to Notification preferences, selecting Telegram, then clicking the switch to "Allow Notifications" showed all notification types as options:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/6933976/149634979-fa41a268-49d2-47b5-9779-a57df757a3b9.png">
