### ISSUE TITLE
Voice records as 2x speed on Monterey with AirPods Pro

### ISSUE THREAD

**Issue by CrazySky2121** [overtake/TelegramSwift#692]
When I using AirPods Pro with telegram on Monterey and trying to record voice - record obtained with 2x speed.

In others apps or when I using micro from MacBook everything is fine.

**Comment by AlexanderSukhanov** [comment]
Same for me

**Comment by CrazySky2121** [comment]
@overtake Please fix

**Comment by makmary170** [comment]
+

**Comment by malyshkin-vitali** [comment]
Same for me. AirPods 3 + MacOS 12. Pls fix it.

**Comment by qtist** [comment]
I see a similar feature where my desktop microphone at 44.1kHz plays back slightly sped up and higher pitch, as if Telegram treats all mic devices as 48kHz whether they are or not. Perhaps there needs to be better use of CoreAudio

**Comment by bastik961** [comment]
Same problem. Telegram - 8.6.228556 (AppStore). MacBook Air M1 (MacOS Monterey 12.3 (21E230)) + AirPods 2

**Comment by choodique** [comment]
Same problem.
AirPods Pro, Apple M1m Telegram 8.6.228674 Stable, macOS 12.3.1

**Comment by dm3ch** [comment]
@qtist Your theory seems to be reasonable. For now, I have found two places where something similar to 48kHz is hardcoded:
https://github.com/overtake/TelegramSwift/blob/13d62c1c03df7dea70bad0f395fb68115f5a0b43/Telegram-Mac/MicroListenerController.swift#L166
https://github.com/overtake/TelegramSwift/blob/fa0bfbe4daa5caa837b48653b73fcd02e85c29c3/Telegram-Mac/AudioRecorder.swift#L279

**Comment by ibrahimrajabli** [comment]
same with me

**Comment by Lotfull** [comment]
Same for me.
Airpods 3, Apple Macbook 16' M1 Pro, macOS Monterey 12.1, Telegram 8.8.1.232774 Stable.

**Comment by dm3ch** [comment]
Just found that there's another official desktop telegram application for macOS. This application is cross-platform (same for Windows, Linux, and macOS) and people in Reddit discussions wrote about 4 years ago, that some advanced macOS integration features were missing that days.

https://desktop.telegram.org/
https://github.com/telegramdesktop/tdesktop

I installed mentioned app, tested a recording from my AirPods pro and the x2 voice speed bug hasn't reproduced. 🎉

**Comment by lezzowski** [comment]
Same here.
Airpods 2. Apple Macbook 13" M1, macOS Monterey 12.4. Telegram 8.9.234962
Anyway is this repo active?

**Comment by jaczkal** [comment]
I like it, conversations are now funnier. Made a good day for several people. Wanted feature 👍

**Comment by MishaChernov** [comment]
Same for me. Airpods 2. Apple Macbook 13" M1, macOS Monterey 12.5.1

**Comment by YahiaAngelo** [comment]
Same for me with AirPods 3

**Comment by theimaginationless** [comment]
Same for me with AirPods Pro

**Comment by VitaliyR** [comment]
Same for me, AirPods Pro

**Comment by vFlagz** [comment]
same for me, AirPods Pro 2

**Comment by nomadedge** [comment]
Same for me. High-pitched records with increased speed. MacBook Pro M2, AirPods 3.

**Comment by stlr00** [comment]
One year, still unfixed @overtake

**Comment by overtake** [comment]
i will check it.

**Comment by VahidJbrl** [comment]
same problem

**Comment by overtake** [comment]
should be fixed in today release (9.3). Appstore will be updated later.

**Comment by VitaliyR** [comment]
Can confirm fixed in `9.3.241538 Stable` finally. Thanks!

**Comment by CrazySky2121** [comment]
Thanks! It worked!

**Comment by dmitrymaslov99** [comment]
Not fixed. Instead of 2x - now just silence

**Comment by MishaChernov** [comment]
Confirm, works fine now. Thanks
