### ISSUE TITLE
bot usernames not automatically added to commands selected from suggestions

### ISSUE THREAD

**Issue by l2dy** [overtake/TelegramSwift#71]
https://core.telegram.org/bots#commands
>If multiple bots are in a group, it is possible to add bot usernames to commands in order to avoid confusion:
```
/start@TriviaBot
/start@ApocalypseBot
```
>This is done automatically when commands are selected via the list of suggestions. Please remember that your bot needs to be able to process commands that are followed by its username.

When I use tab to select a command from suggestions, this is not done automatically in Telegram for macOS.

The bot I used has privacy mode enabled, so it can only receive commands explicitly meant for them (e.g. /command@this_bot) in my case. https://core.telegram.org/bots/faq#what-messages-will-my-bot-get

**Comment by zweeltow** [comment]
Looks like this fixed.

**Comment by l2dy** [comment]
> Looks like this fixed.

I can still reproduce this in version 7.2.4. *Tab* completion (with the tab key) won't append the bot username, but clicking on the command does.

**Comment by zweeltow** [comment]
Actually, I am not sure that’s a bug then. Need to ask @overtake.
