### ISSUE TITLE
App not working on macOS High Sierra

### ISSUE THREAD

**Issue by raisty** [overtake/TelegramSwift#73]
Latest update causes problem on macOS High Sierra version: 10.13.2
Telegram version 3.7.2.113207 AppStore.
Used: dark theme, protected by passcode.
Telegram cannot get latest messages while running.
Some areas cannot be accessed in settings.
Even restart of telegram cannot get latest messages.
Reinstallation and change theme + remove passcode cannot solve problem.

Android application works well.

**Comment by overtake** [comment]
try to relogin please.

**Comment by raisty** [comment]
No success. Still same problem.

**Comment by overtake** [comment]
intresting. please contact me in telegram t.me/vihor

**Comment by raisty** [comment]
Thank you.
Seems relogin + wait cca 5 minutes solve my issue.
