### ISSUE TITLE
[Encryption Key] Can't see the E2E encryption key

### ISSUE THREAD

**Issue by dreamwhite** [overtake/TelegramSwift#751]
Hi there,
first of all thank you so much for the effort you're putting in this project.
I'm sorry if this issue was eventually opened but I couldn't find any reference in this GitHub repository.
Basically, the way to reproduce this bug are the following:

- Create a secret chat with a contact
- Click on his username, where you should see the details like username ecc...
- Click on "Encryption Key" button.

Theoretically the Encryption key should be displayed BUT in the latest release (8.5.226936 Stable) clicking the button doesn't show anything.
Is this an issue you're aware of? If so, how can I help you fixing this?
Kind regards
dreamwhite

**Comment by jaekwon** [comment]
I still don't see it.
