### ISSUE TITLE
Telegram stopping after photo drag&drop to chatlist

### ISSUE THREAD

**Issue by Modelair** [overtake/TelegramSwift#76]
Steps: 
1 Receive photo from contact1 
2 dragdrop photo into chat-list to contact2 existing chat

macOS 10.13.2
Telegram 3.7.2.113295 Beta

**Comment by overtake** [comment]
strange. i can't reproduce.

**Comment by overtake** [comment]
can you contact with me? t.me/vihor

**Comment by overtake** [comment]
ok. i found some race condition in this case.  I'm uploading new beta please try again.

**Comment by Modelair** [comment]
it's stops just after DD started, chat-list, probably, not related
