### ISSUE TITLE
Picture background

### ISSUE THREAD

**Issue by vdsirotkin** [overtake/TelegramSwift#77]
Hello. Is there any way to set custom background image? I've only found rgb codes of background colors inside of theme pallettes. Maybe there is another way which i am missing? Thanks.

**Comment by overtake** [comment]
available in beta. And soon in store

**Comment by jeff-h** [comment]
Nice! Unfortunately for me this feature is slightly broken in `v3.7.4.115214 Beta`.

I have an external monitor plugged into my MacBook and when I drag the app window from one screen to another, the chosen background image changes back to plain white.

**Comment by overtake** [comment]
fixed. thanks.

**Comment by vdsirotkin** [comment]
Thanks for implementing! Is there any way to set my own photo as background, or only predefined for now?
