### ISSUE TITLE
[Feature Request] 🕓 Schedule Message -> When Previous Is Read

### ISSUE THREAD

**Issue by bezustally** [overtake/TelegramSwift#780]
### Hello, Telegram!

<br>

_I know this is a rather rare case, but.._

Sometimes, you just need to postpone sending a particular message until your recipient has read something you sent earlier:
- to create some effect or for some other reason (maybe you’re just overloading him/her with information, and you don’t want to increase the counter of unread chat messages)
- perhaps you don’t want the recipient (or someone behind) to peep at messages through the device’s Notifications

— In sum, you just want some part of your message to be sent only when recipient open the chat

Thanks to the team, we already have 2 options in scheduling menu: picking datetime & send when online.
This can be extended with another option "Send when previous message is read".

I don't know the complexity of implementing this feature, but I would even try to make it myself if there are more than one people who want to have this feature in our favourite messenger 😊

### In UI it might look like this:

<img src="https://user-images.githubusercontent.com/63110847/170895768-2ba3344a-23c2-4458-8174-eb82d5e5c5b1.jpg" width="450">

### Thanks for the attention

**Comment by zweeltow** [comment]
This is not specifically about macOS client of Telegram.

You can suggestions feature for Telegram on [Telegram’s Bugs & Suggestions platform](https://bugs.telegram.org/). Read [the platform tip](https://bugs.telegram.org/c/746) before creating first card.
