### ISSUE TITLE
Spurious Alert: "Warning! Your Mac is running low on disc space...."

### ISSUE THREAD

**Issue by madranet** [overtake/TelegramSwift#781]
Telegram version:

![SS 2022-06-01 at 13 25 33](https://user-images.githubusercontent.com/669658/171406815-a1afa0e0-adb0-48a1-8a69-8e38e184a4e8.png)

OSX version:

![SS 2022-06-01 at 13 42 07](https://user-images.githubusercontent.com/669658/171406936-bc64c518-1a76-4001-8c3c-0cdfaf5ca505.png)

I've had this alert popup in Telegram a few times today:

![SS 2022-06-01 at 13 25 22](https://user-images.githubusercontent.com/669658/171406208-e5ef2783-6fd8-4add-8746-8d3eb65c8357.png)

It's completely bogus, as I have plenty of disc space left:

![SS 2022-06-01 at 13 25 58](https://user-images.githubusercontent.com/669658/171406315-310848d4-adb3-4336-9adf-d00e2e6fca1c.png)

And my Telegram data storage prefs are set to unlimited cache size:

![SS 2022-06-01 at 13 35 26](https://user-images.githubusercontent.com/669658/171406405-89fc0ea7-b513-4f38-9205-b70633919dae.png)

I think Telegram self-updated yesterday, or the day before, to the version shown at the top. So I'm assuming this is a newly introduced bug, as I've never seen this alert before.

**Comment by Pyanne** [comment]
Some application (Telegram or another one) maybe leaking memory. Your swap increases till your hard disk is full.
Open Activity Monitor and go to the "Memory" tab to see where this memory pressure comes from.

**Comment by madranet** [comment]
Sorry. I forgot to come back and close this thread.  

It turned out to be an OSX bug, whereby Finder is prone to incorrectly reporting free disc space.  It just happened to coincide with an update to Telegram and Telegram flagging up the [supposed] lack of space.

This was actually one of those rare cases when _"Have you tried turning it off and on again?"_ was the correct answer. A reboot solved the problem.

For now.
