### ISSUE TITLE
[Bug] App crash after click on link with 100% probability

### ISSUE THREAD

**Issue by yan-py** [overtake/TelegramSwift#785]
**The application crashes with 100% probability after clicking on a link like "https://t.me/c/-1000000000000/0" inside the application.**

The last few lines of the log before the application crashed:

_[MT] 2022-6-7 19:25:58.241 [MTProto#0x600001a6d8c0@0x60000137ca00 preparing msgsAck (7106535171832315904/0)]
[MT] 2022-6-7 19:25:58.241 [MTProto#0x600001a6d8c0@0x60000137ca00 preparing channels.getChannels(id: [TelegramApi.Api.InputChannel.inputChannel(channelId: 1001665905031, accessHash: 0)]) (7106535171832689664/0)]
[MT] 2022-6-7 19:25:58.241 container (7106535171833170944) of (7106535171832689664), in 4513489563544758559
[MT] 2022-6-7 19:25:58.319 [MTProto#0x600001a6d8c0@0x60000137ca00 [104] received <MTRpcResultMessage:0x6000025e84a0> (710653     5172183559169, 5286412963424696876/4513489563544758559)]
[MT] 2022-6-7 19:25:58.319 [MTRequestMessageService#0x600000b3c180 response for 7106535171832689664 is error: 400: CHANNEL_INVALID]_

App version: **8.7.1.229827 Stable**

**Comment by zweeltow** [comment]
Looks like this is fixed on latest versions.

**Comment by yan-py** [comment]
> Looks like this is fixed on latest versions.

Confirm, work correct on 8.8.1.232774 Stable
