### ISSUE TITLE
High Memory consumption

### ISSUE THREAD

**Issue by nickaleks** [overtake/TelegramSwift#79]
I have noticed that telegram client consumes a huge amount of ram, at least 2 times more than Telegram Desktop. Is it a bug or just current state of the app?

OS version: macOS 10.13.2 (17C88)

![image 2018-01-10 09 43 00](https://user-images.githubusercontent.com/14168731/34759033-c0cede7c-f5ea-11e7-8d7a-ee9ccc9ef8ec.jpg)

**Comment by robsonpeixoto** [comment]
The same here:

macOS 10.13.2 (17C205)

![image](https://user-images.githubusercontent.com/124390/34993637-b6bac832-faaf-11e7-8e58-fcd136d52281.png)

**Comment by overtake** [comment]
found some bugs. Fixed.
