### ISSUE TITLE
Telegram Premium functionality is not available

### ISSUE THREAD

**Issue by mammuthus** [overtake/TelegramSwift#790]
Telegram Premium functionality doesn't work on the latest stable release (8.7.1.229827 Stable)

Warning message from the public chat:
![CleanShot 2022-06-20 at 02 06 21@2x](https://user-images.githubusercontent.com/1700286/174502122-d882a716-37eb-477f-ae72-6d408674af4e.png)
If "UPDATE" was pressed:
<img width="330" alt="CleanShot 2022-06-20 at 02 07 09@2x" src="https://user-images.githubusercontent.com/1700286/174502137-b0dbecc3-40de-4fff-aff9-ac1e5df0e653.png">

Also there is no premium badge near premium accounts name and other stuff is not available either.

**Comment by koval01** [comment]
I'm also waiting for this update for mac as soon as possible

**Comment by koval01** [comment]
> Right now I got an update (8.8.232668 Stable). Userpic animations still not visible in public chats.

Yes, avatars are not lost in groups. I think the developer did it specifically for optimization.

**Comment by mammuthus** [comment]
Finally, in today's update (8.8.232680 Stable) userpics became animated in public chats :)

**Comment by koval01** [comment]
So I see, thank you to the developer for your efforts. But the question still remains, will the star appear next to the username in all scenarios? This is now a chat list, personal chat and profile. I would like to see premium users in public chats and comments. Maybe Telegram in its user API does not provide this information in the message structure, I do not know.

**Comment by VadimMuhtarov** [comment]
When 8.8 will be released? Still 8.7.1 in App Store

**Comment by overtake** [comment]
Download app directly from macos.telegram.org

In AppStore app in review for a week!
