### ISSUE TITLE
Missing swap action "archive" 

### ISSUE THREAD

**Issue by Haarolean** [overtake/TelegramSwift#792]
Before the latest version left swipe made the chat archived. There's "delete" action instead now. That's a dangerous change and I'd like to swipe chats to make them archived.
before:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1494347/174861504-bce81e62-ff83-470b-aaf1-c5204737ef66.png">
after:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/1494347/174861778-5b2c65ce-3080-4667-8a2c-1ce885e5fc86.png">

**Comment by gutobenn** [comment]
I'm missing it too!

**Comment by gutobenn** [comment]
@Haarolean It's back! :)

**Comment by runegan** [comment]
I'm still missing this on newest version. The swipe to archive feature is there in the "all chats" folder, but not in any other, as it is in the mobile version.

**Comment by kopyl** [comment]
@gutobenn hey :)

I'm developing a [macOS app](https://github.com/kopyl/safari-tab-switcher) and want to implement the same swipe actions as those in Telegram app.

Could you please guide me towards the solution? The codebase is very large so it's very hard to find useful info.
I just started learning Swift 3 months ago so i'm just lost.

But I love how it works in Telegram.

**Comment by gutobenn** [comment]
@kopyl Hi! I just commented here as an user, I don't have experience in this codebase

**Comment by kopyl** [comment]
@gutobenn my bad, sorry
