### ISSUE TITLE
Option to disable video-avatars animaiton in chats list

### ISSUE THREAD

**Issue by PiN73** [overtake/TelegramSwift#795]
New video-avatars-everywhere are fun, but can be disturbing for some people. It's hard to concentrate on work messages when something is animating nearby. I suggest adding an option to disable the animation, just like "Loop animated stickers" can be disabled

**Comment by zweeltow** [comment]
This is not specifically about macOS client of Telegram.  

You can suggestions feature for Telegram on [Telegram’s Bugs & Suggestions platform](https://bugs.telegram.org/). Read [the platform tip](https://bugs.telegram.org/c/746) before creating first card.

**Comment by PiN73** [comment]
@zweeltow why, isn't the client choosing to play a video or not?
