### ISSUE TITLE
Failed to display the normal UI

### ISSUE THREAD

**Issue by EvanLuo42** [overtake/TelegramSwift#797]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/62578958/176982023-d935de4d-0837-4582-9bfa-e1aff911e867.png">

After open the app, it showed like the image above.

OS: macOS 13.0

**Comment by EvanLuo42** [comment]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/62578958/176982388-0b2469b3-4832-4bb5-af0f-ba1f8f97776a.png">

**Comment by Boyee2022** [comment]
I find the same question

**Comment by ours1505** [comment]
I find the same question
how to fix it?
