### ISSUE TITLE
Music stops when changing accounts

### ISSUE THREAD

**Issue by theablemo** [overtake/TelegramSwift#799]
### Steps to reproduce

1. Play any music in account 1
2. Switch to account 2

### Expected behavior

Music should keep on playing. It is the default behavior on the mobile version of Telegram.

### Actual behavior

The music stops after switching accounts.

### Configuration

- Operating system:
MacOS 12.4 - Macbook Pro M1Pro
- Version of Telegram Desktop:
8.8.1.232774 Stable

**Comment by alerezaaa** [comment]
Hi
Just a small reminder on version `9.5.2.244826 Stable` its still missing

Also I have to note that this is default behavior on traditional Telegram-Desktop client

Thanks

**Comment by arsamme** [comment]
Any updates on this?
Music also stops when Telegram gets locked using local passcode.
