### ISSUE TITLE
Convert double dash to em dash (long dash)

### ISSUE THREAD

**Issue by user334** [overtake/TelegramSwift#801]
Hi! 
So the request is simple: the original ("Lite") Telegram Desktop app converts double dash ("--") to one em dash ("—") and reverts this by pressing backspace after that. Since those are a different symbols used for different things and a double-dashes looks worse I really really miss this feature that's why I'm kindly ask you to implement this feature here too :)

**Comment by zweeltow** [comment]
Try https://t.me/macswift/70853.

**Comment by user334** [comment]
@zweeltow 
That's kinda works. Thanks! (a new macos user here, didn't know about this setting yet)
But I'm not sure whether we should rely on this system thing or not 🤔
