### ISSUE TITLE
Navigation through control + [num] doesn't work anymore

### ISSUE THREAD

**Issue by StayInLight** [overtake/TelegramSwift#802]
Previously telegram got ability to navigate between chats through `contol + [num]` in folders. Now it doesn't work

**Comment by StayInLight** [comment]
I found new way to navigate here: https://github.com/overtake/TelegramSwift/wiki. Could you pls give an opportunity to use old style shortcut

**Comment by zweeltow** [comment]
> I found new way to navigate here: https://github.com/overtake/TelegramSwift/wiki. 

Actually it was like that when folders were released.  

> Could you pls give an opportunity to use old style shortcut

This is so bad, ⌃[num] using by macOS for [switching between screens](https://support.apple.com/en-us/HT204100).
