### ISSUE TITLE
Light - Dark mode does not respect current system appearance

### ISSUE THREAD

**Issue by panosru** [overtake/TelegramSwift#815]
If you set Appearance to "System", meaning that it has to respect the **current** system appearance (either dark or light mode), Telegram will behave strangely.

1. While running, once the time to switch from either Light to Dark or Dark to Light, the Telegram app also switches.
2. If you don't have Telegram running when the switch happens for the system, then Telegram will open with the last appearance state.

Scenario A:
You boot your computer in the morning, running Telegram (Light mode), then at noon you close Telegram, continue your work, somewhere about evening the system switches to dark mode, then you open Telegram again, it is still in light mode, if Telegram wasn't running, it does not check on app start what is the current system appearance mode.

Scenario B (continue from scenario A):
You shut down your computer at night, meaning your last system appearance mode was in dark mode, then in the morning you boot your computer and open your daily apps, including Telegram. All apps are in light mode (since it is morning), except Telegram which is in the dark mode because that was the mode when you last used it.

In order to make telegram use the current appearance mode, once you open it, you have to quit the app and open it again, and then it will open in the proper system appearance mode.

**Comment by brimarq** [comment]
Same issue here.

**Comment by Write** [comment]
Can confirm the issue, I just wrote about it here https://github.com/overtake/TelegramSwift/issues/764#issuecomment-1261973064 I have to say after months and months it really drives me crazy. 
Even the Scheduled auto-switch doesn't work for me. Not only following the system.

**Comment by kambala-decapitator** [comment]
just experienced scenario B as well

**Comment by panosru** [comment]
I am closing the issue since it is a duplicate of #764 as @Write mentioned.

PS: The issue still persists with v9.0.1.237033 Stable
