### ISSUE TITLE
Dead Instant View Windows When In Full Screen

### ISSUE THREAD

**Issue by BenjaminWKI** [overtake/TelegramSwift#83]
When using Instant View to view a shared URL when Telegram is in fullscreen mode, the user will be trapped in there and unable to "Escape" or close the Instant View window. There is no visible 'Back' or 'Exit' button or link. Pressing the 'Esc' key does nothing. Getting out of full screen won't bring the needed buttons. 
The only way is to 'Cmd + Tab' to switch task over back to the Telegram message window, but that leaves a full blacked out desktop. If one were to use the Instant View link again, it adds another blacked out desktop. These dead desktops will only be restored after shutting down Telegram.

**Comment by Scukerman** [comment]
Ran into this issue today.

**Comment by Andrew-Shtein** [comment]
Same "dead screen" thing also after closing Instant View window by CMD+W.

**Comment by zweeltow** [comment]
Fixed.
