### ISSUE TITLE
Sending a message with one emoji makes app unresponsive

### ISSUE THREAD

**Issue by ruiramos** [overtake/TelegramSwift#84]
Sending a message with one emoji and pressing enter makes the app unresponsive for a few seconds (showing the macos spinning beach ball). I suspect this is related to the app trying to load the stickers at the same time as it's sending the message.

Steps to reproduce:
1. Create a chat
2. Type :)
3. Press enter.
The app hangs.

Telegram version: 3.7.3.114679

**Comment by overtake** [comment]
i can't reproduce ;(

**Comment by ruiramos** [comment]
Actually I think in my case it happens whenever I _finish_ a message with an emoji (ie, the last character is either an emoji already or will be replaced by one, like in the :) case).
Is there any debugging I'd be able to do?
Thanks a lot!

**Comment by ruiramos** [comment]
Hi @overtake sorry bothering you with this again. I'm on 4.1 and this still happens: when I finish a message with an emoji, or something that gets replaced by an emoji, I can the spinning beach ball for a good 5 seconds, making the app unresponsive.
I understand that this might be hard to reproduce (otherwise it would have been found and fixed already) so my question is: do you have any suggestions on how I could debug this further?
Thanks!

**Comment by ruiramos** [comment]
Seems to have been fixed in 4.2 somehow? Can't find the changelog but it's not happening anymore since I updated today. Thanks! 👍
