### ISSUE TITLE
Animated emojis are still suggested, even if the option is disabled

### ISSUE THREAD

**Issue by d4rky-pl** [overtake/TelegramSwift#840]
Even with this option disabled:

<img width="627" alt="Screenshot 2022-09-28 at 15 30 00" src="https://user-images.githubusercontent.com/284395/192791381-c64af8a2-929d-4b38-99e3-f76067a2ad03.png">

I'm still seeing cringy animated emojis whenever I use `:` to add a regular emoji

<img width="577" alt="Screenshot 2022-09-28 at 15 30 30" src="https://user-images.githubusercontent.com/284395/192791490-557a425a-5b6d-416f-b072-c6512ef0483e.png">

Is there a way to disable animated emojis other than cancelling Premium?

**Comment by smiba** [comment]
I really wish this wasn't the case, I hate these terrible animated emoji's so badly and the fact they're always suggested before the regular ones is very inconvenient. 

Would actually consider cancelling my Premium just to get rid of them as they slow down my message writing process. I want to be able to write `:sob:` and have the 😭 emoji being suggested first, not some crying animated duck.

**Comment by smiba** [comment]
Unfortunate this is still an issue :(

Started to use my MacBook more often and this is incredibly frustrating, I never wish to use these animated emojis and don't want to have them suggested before the actual regular emoji.

**Comment by WoodyWoodsta** [comment]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/8268040/221905401-889418b2-345f-4122-b66b-6adf7bfaa32a.png">

It's incredibly bad.

**Comment by matthewmorek** [comment]
There's another problem: even if you scroll selection via keyboard all the way to the end of this dreaded list, the view doesn't scroll with the cursor, which means you need to scroll with your mouse/trackpad to see whether you've got the right emoji highlighted before inserting it into the editor.

**Comment by d4rky-pl** [comment]
@overtake any plans to tackle this or is this an intended behaviour?

**Comment by d4rky-pl** [comment]
bump

**Comment by overtake** [comment]
I will take a look tomorrow on this bug

**Comment by emctague** [comment]
Hi, this is still not fixed. I can confirm that the iOS version of Telegram, which has the same setting in it, *does* work properly.

**Comment by matteocontrini** [comment]
@overtake could you take a look at the issue again, please? 🙏 It's still an issue.

**Comment by d4rky-pl** [comment]
Still broken

**Comment by d4rky-pl** [comment]
bump

**Comment by HeySora** [comment]
Still a shame that it is impossible to recommend Premium for that reason alone. I really hope it is going to get fixed soon, it's already been more than a year

**Comment by smiba** [comment]
For me this seems to have been recently fixed on 10.2.2.255063 Stable

Unfortunately the commits to this repo are a mess so I can't figure out when exactly this has been patched though

**Comment by d4rky-pl** [comment]
Still a bug on `10.2.254873 Stable`

**Comment by d4rky-pl** [comment]
I can confirm the problem has been resolved on `10.2.2.255063 Stable`. There's still a visual glitch where the animated emojis flash for a moment before being replaced with the regular one but I'm already happy with it.

Closing the issue.

**Comment by d4rky-pl** [comment]
Broken again in `10.2.3.255286 Stable` ...

**Comment by piankma** [comment]
Can confirm, worked kind-of correctly yesterday on `10.2.2.255063` - it was suggesting standard ones first. Broken today on `10.2.3.255286`

**Comment by vaaski** [comment]
Broken on `10.3.256373 Stable`.
This is the sort of thing that wants me to go back to the cross-platform desktop app and just live with telegramdesktop/tdesktop#17397

<img width="751" alt="image" src="https://github.com/overtake/TelegramSwift/assets/17879327/f371884f-6775-4320-927b-016a179684a4">

**Comment by d4rky-pl** [comment]
@overtake

**Comment by d4rky-pl** [comment]
Welcome in 2024 where this is still not fixed

**Comment by overtake** [comment]
I will take a look at it

**Comment by d4rky-pl** [comment]
bump

**Comment by d4rky-pl** [comment]
bump

**Comment by smiba** [comment]
Still dealing with this yeah, it's quite annoying. If it's any easier, would it just be possible to disable the suggested default animated emoji's? (without disabling suggestions for animated emoji's you've explicitly added)

**Comment by MatteoCampinoti94** [comment]
I don't eve have the option to hide them and when I try to use `:<emoji name>` I have to scroll through _tens_ of horrible animated emojis to reach the actual one :/

![Screenshot 2024-06-11 at 23 04 09](https://github.com/overtake/TelegramSwift/assets/5142004/f5f9cbe4-afc4-4351-badb-8a1d2d2aafa6)

This is honestly the first time for me that something paid has _more_ bugs than the free version 🤦

**Comment by d4rky-pl** [comment]
This issue will likely never be fixed so I'm closing it so I don't get any more notifications

**Comment by matteocontrini** [comment]
@d4rky-pl closing an issue doesn't unsubscribe anyone, you can unsubscribe with the "unsubscribe" button in the sidebar. Please reopen the issue. Thanks

**Comment by smiba** [comment]
@d4rky-pl 

Huh, this is such an odd and unproductive thing to do, just unsubscribe from the issue? 

I can understand that constantly receiving notifications about this may affect you, and I understand, but in that case just unsubscribe. I'm still hoping this issue gets resolved at some point

Please reopen it
