### ISSUE TITLE
UI failed to load emojis, images, stickers etc..

### ISSUE THREAD

**Issue by quocnguyen** [overtake/TelegramSwift#844]
macos mojave 10.14.6
telegram 9.0.1.237033 Stable

here is some screenshots:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/1527816/194011723-e4238c2b-2fcd-4b48-9d8f-ecaabda4db6c.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/1527816/194011901-4f5b7543-c59e-4966-b3fa-934d5b5206fd.png">

<img width="379" alt="image" src="https://user-images.githubusercontent.com/1527816/194011987-040b5567-16c8-4bbf-81dd-b59d198d536d.png">

**Comment by diimdeep** [comment]
I have the same issue

9.0.1.237033 Stable
macOS Catalina 10.15.7
Intel Iris 1536 MB

Graphics glitches appeared in Telegram Client, in:
- in inline image previews
- in emojis to the point that they disappear
- in stickers

Until few weeks ago there wasn't any kind of similar problems ever.

![Screenshot 2022-10-08 at 23 18 25](https://user-images.githubusercontent.com/485713/194726724-31b9314e-ccaf-4805-91b9-2fa29c969d21.png)

![Screenshot 2022-10-08 at 23 18 12](https://user-images.githubusercontent.com/485713/194726723-81a142a8-7b32-4673-8086-08f9330dc6f5.png)

**Comment by diimdeep** [comment]
@zweeltow

**Comment by internetdesu** [comment]
same 9.0.1 (237048)
Mojave 10.14.6
Intel Iris Plus Graphics 640 1536 MB
![telegram-cloud-photo-size-2-5278277716455571502-x](https://user-images.githubusercontent.com/62903401/195170874-1ecc6ebe-2a6e-4ad1-9cc4-fac92e0ab39c.jpg)

**Comment by strokovok** [comment]
Same issue (9.0.1.237033 Stable)
Mojave (10.14.6)
MacBook Pro 2018 / Intel UHD Graphics 630 1536Mb
Appeared few weeks ago, client restart/reboot/storage cleaning doesn't help
<img width="628" alt="image" src="https://user-images.githubusercontent.com/1254210/196833353-08db9c77-44f8-4027-a979-2f3e363cf68f.png">

**Comment by diimdeep** [comment]
Seems like it is related to older macos version <11

**Comment by diimdeep** [comment]
BETA 9.0.1.238224 fixed problem https://install.appcenter.ms/users/keepcoder/apps/telegram-swift/distribution_groups/public

**Comment by quocnguyen** [comment]
Version 9.1.1.238861 Stable fix the issue. Thanks.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/1527816/200735379-caedc266-dcd4-49ba-ac90-17cbd03672b6.png">
