### ISSUE TITLE
Replace Emoji Automatically (disable) option?

### ISSUE THREAD

**Issue by clarkewd** [overtake/TelegramSwift#852]
Looking at previous issues https://github.com/overtake/TelegramSwift/issues/418 and https://github.com/overtake/TelegramSwift/issues/585 it appears that there was previously an option to Enable/Disable replacing emoji automatically:

![80707875-c1bc7800-8afb-11ea-9615-418b8a5dbe7e](https://user-images.githubusercontent.com/156377/197001082-7921af53-de7e-4153-93e9-09005b2c9e52.png)

However this option does not appear to exist under "Emoji and Stickers" or any other menu option:

![Screen Region 2022-10-20 at 12 07 34](https://user-images.githubusercontent.com/156377/197001415-6e78e034-d4cf-405f-aa86-cbe4e9268a8e.png)

I'm using `9.0.1.237033 Stable` which I believe is the latest version.

### Could you please add back the option to disable automatic emoji replacement?

**Comment by smiba** [comment]
You're looking in the wrong place, the options you're looking for are in General (Not the "Stickers & Emoji" setting)

**Comment by clarkewd** [comment]
Thank you so much!
