### ISSUE TITLE
No badge notification when a chat/group is muted

### ISSUE THREAD

**Issue by ShintoPlasm** [overtake/TelegramSwift#88]
In the Telegram Desktop edition, there is a config option whereby you can still get a badge on your dock icon even when a chat/group is muted. This is extremely useful for me, as I would still like to know that some activity has taken place in a group chat - but without being notified of it every time.

I admit this is not really an _issue_, more of a feature request. Many thanks in advance!

**Comment by ekumanov** [comment]
Is it possible to have this option in the newest macOS desktop client? I need to be able to see a badge counter for unmuted chats. Is it closed because it's not technically possible in the Swift edition of the client?

**Comment by ekumanov** [comment]
Sorry, I meant I need to see badge counter for muted chats (not unmuted).
