### ISSUE TITLE
notifications sound ignores system prefs

### ISSUE THREAD

**Issue by terion-name** [overtake/TelegramSwift#89]
I have an external usb audio set as a default system output. But notification sounds in app are bubling via notebook speakers

**Comment by overtake** [comment]
I can't control this behaviour.

https://github.com/overtake/TelegramSwift/blob/e04d88acdbc827827da0c06ccde3cee2dcff2743/Telegram-Mac/ApplicationContext.swift#L826-L852

**Comment by danlugo92** [comment]
> I can't control this behaviour.
> 
> https://github.com/overtake/TelegramSwift/blob/e04d88acdbc827827da0c06ccde3cee2dcff2743/Telegram-Mac/ApplicationContext.swift#L826-L852

You say you cannot control it but in the snippet provided you kinda do..? I don't follow. Or do you mean there's no API to have it use the default sound OR there's a API but it cannot be used because of some kind of limitation?
