### ISSUE TITLE
Ability to hide side panel

### ISSUE THREAD

**Issue by yochem** [overtake/TelegramSwift#91]
It would be nice if the Telegram had the ability of hiding the side panel 😄. In the General Settings I found something called side panel (Well, i think; my application is in dutch), but there appears to be no difference.

**Comment by yochem** [comment]
thanks! It would still be great if there would be a button for it.

**Comment by ronilaukkarinen** [comment]
Voting yes for the button. I prefer app wider without the side panel, but I guess I'll go with this 650px window for now...
