### ISSUE TITLE
Add markdown code snippet syntax

### ISSUE THREAD

**Issue by Scukerman** [overtake/TelegramSwift#92]
I miss qt-version code snippet formatting syntax:

\`single line code snippet\`

\```
mutiline
code snippet
 \```

Would love to see it here.

**Comment by GhostRussia** [comment]
Possible bug with formatting.

work only:
`
```single line code snippet```
`
or
```
```mutiline
code
snippet```
```

not worked:
``````
```
mutiline
code
snippet
```
``````
or 
``````
```mutiline
code
snippet
```
``````
![screenflow](https://user-images.githubusercontent.com/12181586/36243758-8ab92070-1266-11e8-9a88-83551f2b8cc3.gif)

**Comment by GuiSim** [comment]
From what I can tell, this already works.

Triple backtick, single backtick, double asterix, double underscores all work for large code snippet, short code snippet, bold and italic respectively.

You can also select the text, right click, formatting and apply "Monospace"
