### ISSUE TITLE
Prefs in own window

### ISSUE THREAD

**Issue by jeff-h** [overtake/TelegramSwift#93]
Hi — love this app. Thanks for your work, it's really slick!

One request — could you put the app settings into their own preference window, like you'd expect with a native Mac app?

* A big part of the appeal of this app is that it's not just a WKWebView wrapped around a web client, and the latter almost always have their prefs in-situ (eg Slack).
* an example where a separate window would make the UX considerably better would be the Appearance settings — if those were in a separate window, you'd be able to see the effect your changes are having without constantly having to navigate back to your main chat view (yes I know you see a two-message preview in the appearance settings but that doesn't really help with things like previewing the background images in the latest beta).
* the settings are currently quite difficult to reach when you have your main window narrow enough that the four "primary nav" buttons (contacts / calls / chats / settings) are not visible.

**Comment by floam** [comment]
This is closed as completed but preferences still oddly takes you out of the chats.
