### ISSUE TITLE
Issue with Link Preview Alignment for RTL Languages in Latest Telegram Mac Update

### ISSUE THREAD

**Issue by mostafaznv** [overtake/TelegramSwift#940]
Thank you for adding support for displaying RTL languages in the latest update for Telegram Mac.
However, I noticed that there is an issue with displaying link previews for RTL languages. As you can see in the attached screenshot, the thumbnail and summary are not aligned correctly.

Thank you for your attention to this matter.

**Device info**
Telegram macOS 9.4.1 (243742) APP_STORE, MacBook Pro, 13.0

![image](https://user-images.githubusercontent.com/7619687/222493861-c5ad589f-f409-4b6c-a2f1-f3efa79828ee.png)

**Comment by overtake** [comment]
this fixed in beta. thx
