### ISSUE TITLE
bold font blurred 

### ISSUE THREAD

**Issue by fiveh** [overtake/TelegramSwift#944]
after last update (9.5.244422) from appStore on mac os m1 pro bold font is blurred
![IMAGE 2023-03-16 10:46:47](https://user-images.githubusercontent.com/12550241/225549091-5837467e-73f4-492e-bcf2-31d0eaf0fbb4.jpg)

Expected behaviour
normal bold fonts

Actual behaviour
blurred fonts

Operating system
mac os Ventura (v 13.2.1)

Version of Telegram Desktop
9.5.244422

Installation source
Mac App Store

**Comment by FelikZ** [comment]
same here

**Comment by overtake** [comment]
are you using external monitor?

**Comment by fiveh** [comment]
No, it’s retina on MacBook Pro m1 14”

**Comment by overtake** [comment]
interesting. uploading new version. would you able to check?

**Comment by overtake** [comment]
did you read my previous message? I uploading new stable version. it will be available in 1 hour. 244656 build number. Please wait and tell me was it help?

**Comment by overtake** [comment]
https://macos.telegram.org/ version from the site

**Comment by fiveh** [comment]
okey, waiting

**Comment by overtake** [comment]
Updated. Can you check?

**Comment by fiveh** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/12550241/225996634-279d81fd-fe6e-4954-a3b9-a6dfe561df3e.png">
yes it's fixed thanks!

**Comment by FelikZ** [comment]
fixed for me too, thanks.
