### ISSUE TITLE
[AppStore version] lack of Hardened Runtime

### ISSUE THREAD

**Issue by beerisgood** [overtake/TelegramSwift#947]
from https://www.sentinelone.com/blog/15-macos-power-tricks-for-security-pros/ I use this script for checking Apps without using Hardened Runtime and Telegram is listed.

> No Hardened Runtime: /Applications/Telegram.app/Contents/MacOS/Telegram

Script:
`for i in /Applications/*.app; do codesign -dv "${i}" &>> /tmp/codes; done; grep -B3 'none' /tmp/codes | grep ^Executable | sed 's/^Executable=/No Hardened Runtime: /g'; rm -rf /tmp/codes`

i would therefore appreciate it if this is built into Telegram.

**Comment by overtake** [comment]
Interesting. Actually I set hardened runtime when building app.  But I will
check twice tomorrow

**Comment by beerisgood** [comment]
@overtake any updates?

**Comment by beerisgood** [comment]
@overtake I used the script again and Telegram isn't listed anymore so I close this issue as solved 👍
