### ISSUE TITLE
As of version 9.5, custom notifications are gone

### ISSUE THREAD

**Issue by abiusx** [overtake/TelegramSwift#948]
I used the original telegram sound for notifications on iPhone and Mac, and the custom uploaded notification would sync.
As of 9.5 update, the Mac version does not support custom notification files or uploads. It's only the default sounds which are kind of annoying.

Should I find the diff and revert it?

**Comment by overtake** [comment]
fix is coming today.

**Comment by dimkagithub** [comment]
Nope.

**Comment by overtake** [comment]
> > fix is coming today.
> 
> Nope.

available in 9.5.3 on stable and appstore version. appstore version will be in 20-30 min
