### ISSUE TITLE
Telegram Desktop 9.6.245675 Stable shows scrollbar in the list of folders

### ISSUE THREAD

**Issue by dottedmag** [overtake/TelegramSwift#964]
Since the last upgrade, the list of folders has a scrollbar in it. See the screenshot.

<img width="457" alt="Screenshot 2023-04-21 at 17 03 07" src="https://user-images.githubusercontent.com/16120/233669848-76518360-ac5e-470d-9490-dd4285c4b1a5.png">

**Comment by vxna** [comment]
@overtake 
On the chats list as well:
![CleanShot 2023-04-21 at 21 10 39@2x](https://user-images.githubusercontent.com/30002276/233672113-b4e6071b-510c-4374-895b-de0d01acb8dd.png)

**Comment by overtake** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/1260850/233672339-f9c56d7f-5949-4e47-9baf-5c0a0e053a77.png">
try to change system settings.

**Comment by dottedmag** [comment]
More information. This scrollbar is actually a scrollbar of the chat/user list.

It is shown at the top if the list is shorter than the window height (see my screenshot in the bug).

If one switches to a list that is longer than the window height, the scrollbar expands:

<img width="621" alt="Screenshot 2023-04-21 at 17 10 16" src="https://user-images.githubusercontent.com/16120/233672748-1d37bba7-a9a8-4056-9624-593fa479d452.png">

After some scrolling the scroll bar becomes normal:

<img width="625" alt="Screenshot 2023-04-21 at 17 10 22" src="https://user-images.githubusercontent.com/16120/233672886-c1133e7b-5a68-456b-95c8-f94cb9b1e975.png">

After switching back to a list that is shorter than the window height, the scrollbar expands to the whole window:

<img width="543" alt="Screenshot 2023-04-21 at 17 10 09" src="https://user-images.githubusercontent.com/16120/233673031-f24d5ff3-f444-403b-8fd7-7129ecf3ce38.png">

**Comment by vxna** [comment]
@overtake We are reporting here that the behavior is changed since the last update. They are now always visible regardless if the area should be actually scrollable. For myself, I have "Always visible" in settings.

Maybe it was actually bug before though and now it's fixed 🤔

**Comment by overtake** [comment]
yes. its was buggy and fixed in the latest release

**Comment by dottedmag** [comment]
"always".

The issue is that scroll bar is larger than it should be: it goes over the "archived chats" and list of folders.

**Comment by overtake** [comment]
anyway. i improved that case. new version will be soon, please check

**Comment by vxna** [comment]
I see it's now fixed, thank you @overtake 🎉
