### ISSUE TITLE
Bug recoding voice messages

### ISSUE THREAD

**Issue by gasabr** [overtake/TelegramSwift#98]
Version: 3.7.5.115423 Stable
MacOs 10.12.4 (16E195)

How to reproduce a bug:
1. connect bluetooth speakers to the mac
2. try to record the audio in the "Saved messages" chat

Result: the time goes slower than it should. Yes, recording time is not the real time but 3-5 times slower. If I disable speakers everything works fine and in other apps both ways of audio input work as well

**Comment by overtake** [comment]
fixed in beta. wait release
