### ISSUE TITLE
Forwarding several albums works not as expected

### ISSUE THREAD

**Issue by rouqs** [overtake/TelegramSwift#99]
### Steps to reproduce
1. send 13 images as 2 albums(10 in first one and 3 images in second) to your "saved messages" chat. 
2. forward them to another chat/group.
done. 
### Expected behaviour
images are sent as 2 albums as they were in saved messages chat. (as 2 albums, first - 10 images, second - 3 images)

### Actual behaviour
telegram forwards them as : album of 5 images, then 5 images separately(one by one) and then album of 3 images. 

**Additional details** also it changes how it sends images when amount of images changes. for 12 and less images it works as intended, but with 13 and more it starts to divide albums into separate images, for example when you forward 2 albums of 20 images in total, it sends them as: album of 5 images, 6 separate images, album of 2 images,3 separate images, album of 4 images.
**Version** 3.7.3.114679

**Comment by zweeltow** [comment]
Fixed i guess.
